/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module tt_um_clash_mac
    ( // Inputs
      input  rp2040Clk // clock
    , input  ethRxClk // clock
    , input  ethTxClk // clock
    , input  reset // reset
    , input  rx_dv
    , input  rx_err
    , input [3:0] rx_data

      // Outputs
    , output wire  tx_en
    , output wire  tx_err
    , output wire [3:0] tx_data
    );
  wire [4:0] c$ds_app_arg;
  wire [4:0] c$ds_case_alt;
  wire [16:0] c$ds_case_alt_0;
  wire [16:0] result_0;
  wire [11:0] result_1;
  reg [4:0] ds1;
  wire  inReady;
  wire [9:0] inp;
  wire [11:0] result_2;
  reg [89:0] result_3;
  wire [77:0] c$ds_app_arg_0;
  wire [89:0] c$ds_case_alt_1;
  wire [0:0] c$ds_app_arg_1;
  wire [0:0] c$ds_case_alt_2;
  wire [77:0] c$ds_app_arg_2;
  wire [77:0] c$ds_case_alt_3;
  wire [77:0] c$ds_case_alt_4;
  wire [1:0] newLast;
  wire  nextAborted;
  wire [7:0] ds8;
  wire [89:0] c$ds_case_alt_5;
  wire [77:0] c$ds_app_arg_3;
  wire [77:0] c$ds_case_alt_6;
  wire  nextAborted_0;
  wire [79:0] ds9;
  reg [79:0] c$ds9_app_arg;
  wire [9:0] pkt;
  reg [77:0] eta2;
  wire  bwdIn;
  wire [11:0] result_4;
  wire [58:0] result_5;
  wire [58:0] c$ds8_case_alt;
  wire [9:0] c$ds8_app_arg;
  wire [46:0] c$ds8_app_arg_0;
  wire [46:0] c$ds8_case_alt_0;
  wire [46:0] c$ds8_case_alt_1;
  wire [0:0] x;
  wire [1:0] insertCrc;
  wire [39:0] ds14;
  wire [39:0] c$ds14_app_arg;
  wire [39:0] c$app_arg;
  wire [7:0] x1_0;
  wire [39:0] result_6;
  wire [9:0] cache;
  wire [10:0] fwdIn;
  wire [0:0] c$ds8_app_arg_2;
  wire [46:0] c$ds8_app_arg_3;
  wire  r2sAc;
  wire [31:0] result_7;
  wire [31:0] result_8;
  wire [31:0] c$app_arg_0;
  wire [31:0] result_9;
  wire [31:0] c$app_arg_1;
  reg [31:0] crcState;
  reg [31:0] c$crcState_case_alt;
  wire [7:0] x_0;
  wire [31:0] c$app_arg_2;
  wire [31:0] result_10;
  wire [31:0] c$crcState_app_arg;
  wire  c$crcState_app_arg_0;
  wire [7:0] ds11;
  wire [7:0] a1_1;
  wire [8:0] c$x_app_arg;
  reg  c$x_app_arg_1;
  wire  c$x_case_alt;
  wire [9:0] fwdInX;
  wire [9:0] a1_2;
  wire  transferOccured;
  wire  ready;
  wire  c$transferOccured_app_arg;
  wire [11:0] c$case_alt;
  wire [10:0] s2rAc;
  wire [46:0] c$ds8_case_alt_2;
  wire  finished;
  wire [39:0] ds15;
  reg [46:0] ds6;
  wire [11:0] result_11;
  reg [19:0] result_12;
  wire [0:0] c$ds_app_arg_4;
  wire [7:0] c$ds_app_arg_5;
  wire [7:0] c$ds_case_alt_7;
  wire  done;
  wire [5:0] i;
  wire [19:0] c$ds_case_alt_8;
  wire [7:0] c$ds_app_arg_6;
  wire  c$ds_case_alt_9;
  wire [19:0] c$ds_case_alt_10;
  wire [0:0] c$ds_app_arg_7;
  wire [0:0] c$ds_case_alt_11;
  wire [7:0] c$ds_app_arg_9;
  wire  bwd;
  wire [7:0] c$ds_case_alt_12;
  wire  done_0;
  wire [7:0] c$ds_case_alt_13;
  wire [7:0] c$ds_case_alt_14;
  wire [9:0] fwdIn_0;
  wire [5:0] c$ds_app_arg_10;
  wire [5:0] i_0;
  reg [7:0] ds;
  wire [121:0] a1_4;
  wire [122:0] result_13;
  wire [11:0] result_14;
  reg [138:0] result_15;
  wire [126:0] c$ds_app_arg_11;
  wire [138:0] c$ds_case_alt_15;
  wire [0:0] c$ds_app_arg_12;
  wire [0:0] c$ds_case_alt_16;
  wire [126:0] c$ds_app_arg_13;
  wire [126:0] c$ds_case_alt_17;
  wire [126:0] c$ds_case_alt_18;
  wire [1:0] newLast_0;
  wire  nextAborted_1;
  wire [7:0] ds8_0;
  wire [138:0] c$ds_case_alt_19;
  wire [126:0] c$ds_app_arg_14;
  wire [126:0] c$ds_case_alt_20;
  wire  nextAborted_2;
  wire [127:0] ds9_0;
  reg [127:0] c$ds9_app_arg_0;
  wire [47:0] g1;
  wire [47:0] g2;
  wire [15:0] g3;
  wire [47:0] c$app_arg_3;
  wire [47:0] c$app_arg_4;
  wire [111:0] result_16;
  wire [121:0] pkt_0;
  reg [126:0] eta2_0;
  wire  bwdIn_0;
  wire [123:0] result_17;
  wire [246:0] result_18;
  wire [246:0] result_19;
  wire [63:0] c$ds1_case_alt;
  wire [111:0] result_20;
  wire [111:0] ds4;
  wire [63:0] back;
  wire [111:0] c$mapOut;
  wire [111:0] ds14_0;
  wire [246:0] result_21;
  wire  ds11_0;
  reg [123:0] eta5;
  reg [247:0] result_22;
  wire [123:0] c$ds2_app_arg;
  wire [247:0] c$ds2_case_alt;
  wire [0:0] c$ds2_app_arg_0;
  wire [0:0] c$ds2_case_alt_0;
  wire [123:0] c$ds2_app_arg_1;
  wire [123:0] c$ds2_case_alt_1;
  wire [123:0] c$ds2_case_alt_2;
  wire [1:0] newLast_1;
  wire  nextAborted_3;
  wire [7:0] ds10;
  wire [247:0] c$ds2_case_alt_3;
  wire [123:0] c$ds2_app_arg_2;
  wire  readyOut;
  wire  r2sAc_0;
  wire  c$readyOut_case_alt;
  wire [122:0] fwdOut;
  wire [246:0] result_23;
  wire [246:0] c$ds10_case_alt;
  wire  nextAborted_4;
  wire [111:0] combined;
  wire [9:0] pkt_1;
  wire  bwd_0;
  wire [11:0] c$case_alt_0;
  wire [10:0] s2rAc_0;
  wire [6:0] result_24;
  wire [3:0] x_1;
  wire  x_2;
  wire [7:0] ds2;
  reg  nibbleSelect;
  wire  inputVld;
  wire [7:0] c$ds2_app_arg_3;
  wire [9:0] a1_7;
  reg [3:0] c$ds_app_arg_15;
  reg  c$ds_app_arg_16;
  wire [0:0] result_25;
  wire [10:0] result_26;
  wire [10:0] c$case_alt_1;
  wire  dv0;
  wire [3:0] nibble0;
  reg  ds3;
  wire  c$ds_app_arg_17;
  wire [11:0] ds2_0;
  wire [19:0] result_27;
  wire [80:0] result_28;
  wire [80:0] result_29;
  wire [7:0] result_30;
  wire [63:0] c$mapOut_0;
  wire [63:0] ds14_1;
  wire [80:0] result_31;
  wire  ds11_1;
  reg [61:0] eta5_0;
  reg [81:0] result_32;
  wire [61:0] c$ds2_app_arg_4;
  wire [81:0] c$ds2_case_alt_4;
  wire [0:0] c$ds2_app_arg_5;
  wire [0:0] c$ds2_case_alt_5;
  wire [61:0] c$ds2_app_arg_6;
  wire [61:0] c$ds2_case_alt_6;
  wire [61:0] c$ds2_case_alt_7;
  wire [1:0] newLast_2;
  wire  nextAborted_5;
  wire [7:0] ds10_0;
  wire [81:0] c$ds2_case_alt_8;
  wire [61:0] c$ds2_app_arg_7;
  wire  readyOut_0;
  wire  r2sAc_1;
  wire  c$readyOut_case_alt_0;
  wire [18:0] fwdOut_0;
  wire [80:0] result_33;
  wire [80:0] c$ds10_case_alt_0;
  wire  nextAborted_6;
  wire [63:0] combined_0;
  wire [9:0] pkt_2;
  wire  bwd_1;
  wire [11:0] c$case_alt_2;
  wire [10:0] s2rAc_1;
  wire [11:0] result_34;
  wire [17:0] x_3;
  reg [10:0] c$case_alt_3;
  wire [10:0] result_35;
  wire [10:0] s2rAc_2;
  wire  r2sAc_2;
  wire [5:0] result_36;
  wire [5:0] rxChannel;
  wire [10:0] c$ds_case_alt_selection_3;
  wire [10:0] c$ds_case_alt_selection_6;
  wire [10:0] c$ds_case_alt_selection_14;
  wire [7:0] c$ds_case_alt_sel_alt_t_10;
  wire [2:0] c$ds9_app_arg_selection_1;
  wire [63:0] c$ds9_app_arg_sel_alt_res;
  wire [63:0] c$vec;
  wire [10:0] c$ds8_case_alt_selection_1;
  wire [39:0] c$vec_0;
  wire [7:0] x1_projection_1;
  wire [31:0] c$vec_1;
  wire [31:0] c$vec_2;
  wire signed [63:0] c$crcState_case_alt_selection_1;
  wire signed [63:0] c$crcState_case_alt_selection_0;
  wire [7:0] x_projection_0;
  wire [1279:0] c$vec_3;
  wire [10:0] fwdInX_selection_1;
  wire [10:0] c$transferOccured_app_arg_selection_1;
  wire [10:0] c$ds_case_alt_selection_19;
  wire [10:0] c$ds_case_alt_selection_24;
  wire [122:0] result_selection_5;
  wire [7:0] c$ds_case_alt_sel_alt_t_31;
  wire [3:0] c$ds9_app_arg_selection_4;
  wire [111:0] c$vec_4;
  wire [10:0] c$ds2_case_alt_selection_1;
  wire [10:0] c$ds2_case_alt_selection_9;
  wire [111:0] c$ds10_case_alt_sel_alt_f_0;
  wire [10:0] x_selection_2;
  wire [10:0] inputVld_selection_1;
  wire [10:0] c$ds2_app_arg_selection_5;
  wire [7:0] c$vec_5;
  wire [63:0] c$vec_6;
  wire [63:0] c$vec_7;
  wire [10:0] c$ds2_case_alt_selection_12;
  wire [10:0] c$ds2_case_alt_selection_20;
  wire [63:0] c$ds10_case_alt_sel_alt_f_4;
  wire [7:0] c$case_alt_selection_4;
  wire [18:0] result_selection_25;
  wire [5:0] result;

  assign rxChannel = {rx_dv,   rx_err,
                      rx_data};

  assign c$ds_app_arg = (ds1[3:0] == 4'd11) ? {1'b1,4'bxxxx} : {1'b0,ds1[3:0] + 4'd1};

  assign c$ds_case_alt = inp[1:1] ? {1'b0,4'd0} : {1'b1,4'bxxxx};

  assign c$ds_case_alt_selection_3 = result_2[10:0];

  assign c$ds_case_alt_0 = c$ds_case_alt_selection_3[10:10] ? {c$ds_case_alt,
                                                               {inReady,
                                                                result_2[10:0]}} : {{1'b1,4'bxxxx},
                                                                                    {inReady,   {1'b0,10'bxxxxxxxxxx}}};

  assign result_0 = ds1[4:4] ? c$ds_case_alt_0 : {c$ds_app_arg,
                                                  {1'b0,   {1'b0,10'bxxxxxxxxxx}}};

  assign result_1 = result_0[11:0];

  // register begin
  always @(posedge ethRxClk ) begin : ds1_register
    if ( reset) begin
      ds1 <= {1'b1,4'bxxxx};
    end else begin
      ds1 <= result_0[16:12];
    end
  end
  // register end

  assign inReady = result_24[6:6];

  assign inp = result_2[9:0];

  assign result_2 = result_3[11:0];

  always @(*) begin
    case(eta2[77:76])
      2'b00 : result_3 = c$ds_case_alt_5;
      2'b01 : result_3 = c$ds_case_alt_1;
      default : result_3 = {c$ds_app_arg_0,   {1'b0,
                                               {1'b1,eta2[75:66]}}};
    endcase
  end

  assign c$ds_app_arg_0 = bwdIn ? {2'b00,3'd0,{9 {8'b00000000}},1'b0} : eta2;

  assign c$ds_case_alt_selection_6 = result_4[10:0];

  assign c$ds_case_alt_1 = c$ds_case_alt_selection_6[10:10] ? {c$ds_app_arg_2,
                                                               {bwdIn,   {1'b1,{ds8,   c$ds_app_arg_1,
                                                                                nextAborted}}}} : {eta2,   {bwdIn,
                                                                                                            {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_1 = newLast[1:1] ? c$ds_case_alt_2 : 1'd0;

  assign c$ds_case_alt_2 = newLast[0:0] ? 1'd0 : 1'd1;

  assign c$ds_app_arg_2 = bwdIn ? c$ds_case_alt_3 : eta2;

  assign c$ds_case_alt_3 = newLast[1:1] ? c$ds_case_alt_4 : {2'b01,nextAborted,75'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds_case_alt_4 = newLast[0:0] ? {2'b10,{{1 {8'b00000000}},
                                                  1'd1,
                                                  nextAborted},66'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,3'd0,{9 {8'b00000000}},1'b0};

  assign newLast = pkt[1:1] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign nextAborted = eta2[75:75] | pkt[0:0];

  assign ds8 = pkt[9:2];

  assign c$ds_case_alt_selection_14 = result_4[10:0];

  assign c$ds_case_alt_5 = c$ds_case_alt_selection_14[10:10] ? {c$ds_app_arg_3,
                                                                {1'b0,   {1'b1,{ds9[79:72],   1'd0,
                                                                                nextAborted_0}}}} : {eta2,   {bwdIn,
                                                                                                              {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_3 = bwdIn ? c$ds_case_alt_6 : eta2;

  assign c$ds_case_alt_sel_alt_t_10 = pkt[9:2];

  assign c$ds_case_alt_6 = (eta2[75:73] == 3'd7) ? {2'b01,nextAborted_0,75'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,eta2[75:73] + 3'd1,ds9[71:0],nextAborted_0};

  assign nextAborted_0 = eta2[0:0] | pkt[0:0];

  assign ds9 = c$ds9_app_arg;

  assign c$ds9_app_arg_selection_1 = eta2[75:73];

  assign c$vec = ({({7 {8'b01010101}}),8'b11010101});

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 8; i_1 = i_1 + 1) begin : map
    wire [7:0] map_in;
    assign map_in = c$vec[i_1*8+:8];
    wire [7:0] map_out;
    assign map_out = map_in;


    assign c$ds9_app_arg_sel_alt_res[i_1*8+:8] = map_out;
  end
  endgenerate
  // map end

  always @(*) begin
    case(c$ds9_app_arg_selection_1)
      3'd0 : c$ds9_app_arg = {({((((c$ds9_app_arg_sel_alt_res)))),pkt[9:2]}),({1 {(8'd0)}})};
      default : c$ds9_app_arg = {eta2[72:1],({1 {(8'd0)}})};
    endcase
  end

  assign pkt = result_4[9:0];

  // register begin
  always @(posedge ethRxClk ) begin : eta2_register
    if ( reset) begin
      eta2 <= {2'b00,3'd0,{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000},1'b0};
    end else begin
      eta2 <= result_3[89:12];
    end
  end
  // register end

  assign bwdIn = result_1[11:11];

  assign result_4 = {c$case_alt[11:11],
                     result_5[11:1]};

  assign result_5 = ds6[46:46] ? {c$ds8_app_arg_3,
                                  {{1'b1,{ds15[39:32],   c$ds8_app_arg_2,
                                          ds6[45:45]}},   1'b0}} : c$ds8_case_alt;

  assign c$ds8_case_alt_selection_1 = ds6[45:35];

  assign c$ds8_case_alt = c$ds8_case_alt_selection_1[10:10] ? {c$ds8_app_arg_0,
                                                               {{1'b1,c$ds8_app_arg},
                                                                r2sAc}} : {{1'b0,fwdIn,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
                                                                           {{1'b0,10'bxxxxxxxxxx},   1'b1}};

  assign c$ds8_app_arg = insertCrc[1:1] ? {ds14[39:32],
                                           x,   cache[0:0]} : cache;

  assign c$ds8_app_arg_0 = r2sAc ? c$ds8_case_alt_0 : ds6;

  assign c$ds8_case_alt_0 = insertCrc[1:1] ? c$ds8_case_alt_1 : {1'b0,fwdIn,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds8_case_alt_1 = x ? {1'b0,fwdIn,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {1'b1,cache[0:0],fwdIn,((2'b00) - 2'b01),ds14[31:0]};

  assign x = insertCrc[0:0];

  assign insertCrc = cache[1:1] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign ds14 = c$ds14_app_arg;

  assign c$ds14_app_arg = cache[1:1] ? result_6 : ({40 {1'bx}});

  assign c$vec_0 = {x1_0,result_7};

  // reverse begin
  genvar i_2;
  generate
  for (i_2 = 0; i_2 < 1; i_2 = i_2 + 1) begin : reverse
    assign c$app_arg[(1 - 1 - i_2)*40+:40] = c$vec_0[i_2*40+:40];
  end
  endgenerate
  // reverse end

  assign x1_projection_1 = cache[9:2];

  assign x1_0 = x1_projection_1;

  assign result_6 = c$app_arg[39:0];

  assign cache = ds6[44:35];

  assign fwdIn = c$case_alt[10:0];

  assign c$ds8_app_arg_2 = finished ? 1'd1 : 1'd0;

  assign c$ds8_app_arg_3 = r2sAc ? c$ds8_case_alt_2 : ds6;

  assign r2sAc = result_2[11:11];

  assign c$vec_1 = ((result_8));

  // reverse begin
  genvar i_3;
  generate
  for (i_3 = 0; i_3 < 4; i_3 = i_3 + 1) begin : reverse_0
    assign result_7[(4 - 1 - i_3)*8+:8] = c$vec_1[i_3*8+:8];
  end
  endgenerate
  // reverse end

  assign result_8 = 32'b11111111111111111111111111111111 ^ result_9;

  // map begin
  genvar i_4;
  generate
  for (i_4=0; i_4 < 32; i_4 = i_4 + 1) begin : map_0
    wire  map_in_0;
    assign map_in_0 = c$app_arg_1[i_4*1+:1];
    wire [0:0] map_out_0;
    assign map_out_0 = (map_in_0);


    assign c$app_arg_0[i_4*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign result_9 = (c$app_arg_0);

  assign c$vec_2 = ((crcState));

  // reverse begin
  genvar i_5;
  generate
  for (i_5 = 0; i_5 < 32; i_5 = i_5 + 1) begin : reverse_1
    assign c$app_arg_1[(32 - 1 - i_5)*1+:1] = c$vec_2[i_5*1+:1];
  end
  endgenerate
  // reverse end

  // register begin
  always @(posedge ethRxClk ) begin : crcState_register
    if ( reset) begin
      crcState <= 32'b11111111111111111111111111111111;
    end else if (c$crcState_app_arg_0) begin
      crcState <= c$crcState_case_alt;
    end
  end
  // register end

  assign c$crcState_case_alt_selection_1 = c$crcState_case_alt_selection_0;

  assign c$crcState_case_alt_selection_0 = 64'sd0;

  always @(*) begin
    case(c$crcState_case_alt_selection_1)
      64'sd0 : c$crcState_case_alt = result_10;
      default : c$crcState_case_alt = {32 {1'bx}};
    endcase
  end

  assign x_projection_0 = ds11;

  assign x_0 = x_projection_0;

  assign c$vec_3 = {40'b0010000010000000000000000000000000000100,
                    40'b1001000001000000000000000000000000001001,
                    40'b1100100000100000000000000000000000010011,
                    40'b0110010000010000000000000000000000100110,
                    40'b1011001000001000000000000000000001001101,
                    40'b0101100100000100000000000000000010011010,
                    40'b0000110000000010000000000000000000110000,
                    40'b1000011000000001000000000000000001100001,
                    40'b0100001100000000100000000000000011000010,
                    40'b0000000100000000010000000000000010000000,
                    40'b0010000000000000001000000000000000000100,
                    40'b0001000000000000000100000000000000001000,
                    40'b1000100000000000000010000000000000010001,
                    40'b1100010000000000000001000000000000100011,
                    40'b0110001000000000000000100000000001000110,
                    40'b0011000100000000000000010000000010001100,
                    40'b1011100000000000000000001000000000011101,
                    40'b1101110000000000000000000100000000111011,
                    40'b1110111000000000000000000010000001110111,
                    40'b0111011100000000000000000001000011101110,
                    40'b0001101100000000000000000000100011011000,
                    40'b0010110100000000000000000000010010110100,
                    40'b0011011000000000000000000000001001101100,
                    40'b0001101100000000000000000000000111011000,
                    40'b1010110100000000000000000000000010110101,
                    40'b1111011000000000000000000000000001101111,
                    40'b1111101100000000000000000000000011011111,
                    40'b0101110100000000000000000000000010111010,
                    40'b1000111000000000000000000000000001110001,
                    40'b1100011100000000000000000000000011100011,
                    40'b1100001100000000000000000000000011000011,
                    40'b0100000100000000000000000000000010000010};

  // map begin
  genvar i_6;
  generate
  for (i_6=0; i_6 < 32; i_6 = i_6 + 1) begin : map_1
    wire [39:0] map_in_1;
    assign map_in_1 = c$vec_3[i_6*40+:40];
    wire  map_out_1;
    assign map_out_1 = ^ (((({c$crcState_app_arg,((x_0[7:0]))}) & map_in_1)));


    assign c$app_arg_2[i_6*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign result_10 = ((c$app_arg_2));

  assign c$crcState_app_arg = c$x_app_arg_1 ? 32'b11111111111111111111111111111111 : crcState;

  assign c$crcState_app_arg_0 = c$x_app_arg[8:8] ? 1'b1 : 1'b0;

  assign ds11 = c$x_app_arg[8:8] ? a1_1 : ({8 {1'bx}});

  assign a1_1 = c$x_app_arg[7:0];

  assign c$x_app_arg = transferOccured ? {1'b1,fwdInX[9:2]} : {1'b0,8'bxxxxxxxx};

  // register begin
  always @(posedge ethRxClk ) begin : c$x_app_arg_1_register
    if ( reset) begin
      c$x_app_arg_1 <= 1'b1;
    end else if (transferOccured) begin
      c$x_app_arg_1 <= c$x_case_alt;
    end
  end
  // register end

  assign c$x_case_alt = fwdInX[1:1] ? 1'b1 : 1'b0;

  assign fwdInX_selection_1 = c$case_alt[10:0];

  assign fwdInX = fwdInX_selection_1[10:10] ? a1_2 : ({10 {1'bx}});

  assign a1_2 = c$case_alt[9:0];

  assign transferOccured = ready & c$transferOccured_app_arg;

  assign ready = result_5[0:0];

  assign c$transferOccured_app_arg_selection_1 = c$case_alt[10:0];

  assign c$transferOccured_app_arg = c$transferOccured_app_arg_selection_1[10:10] ? 1'b1 : 1'b0;

  assign c$case_alt = (reset) ? {1'b0,
                                 {1'b0,10'bxxxxxxxxxx}} : {ready,   s2rAc};

  assign s2rAc = result_11[10:0];

  assign c$ds8_case_alt_2 = finished ? {1'b0,ds6[44:34],35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {1'b1,ds6[45:45],ds6[44:34],ds6[33:32] - 2'd1,ds15[31:0]};

  assign finished = ds6[33:32] <= 2'd0;

  assign ds15 = ({ds6[31:0],({1 {8'b00000000}})});

  // register begin
  always @(posedge ethRxClk ) begin : ds6_register
    if ( reset) begin
      ds6 <= {1'b0,{1'b0,10'bxxxxxxxxxx},35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else begin
      ds6 <= result_5[58:12];
    end
  end
  // register end

  assign result_11 = result_12[11:0];

  always @(*) begin
    case(ds[7:6])
      2'b00 : result_12 = c$ds_case_alt_10;
      2'b01 : result_12 = c$ds_case_alt_8;
      default : result_12 = {c$ds_app_arg_5,   {1'b0,
                                                {1'b1,{{1 {8'b00000000}},   c$ds_app_arg_4,
                                                       1'b0}}}};
    endcase
  end

  assign c$ds_app_arg_4 = done ? 1'd1 : 1'd0;

  assign c$ds_app_arg_5 = bwd ? c$ds_case_alt_7 : ds;

  assign c$ds_case_alt_7 = done ? {2'b00,6'd0} : {2'b10,i + 6'd1};

  assign done = i == 6'd59;

  assign i = ds[5:0];

  assign c$ds_case_alt_selection_19 = result_14[10:0];

  assign c$ds_case_alt_8 = c$ds_case_alt_selection_19[10:10] ? {c$ds_app_arg_6,
                                                                {bwd,
                                                                 result_14[10:0]}} : {{2'b01,6'bxxxxxx},
                                                                                      {bwd,   {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_6 = (bwd & c$ds_case_alt_9) ? {2'b00,6'd0} : {2'b01,6'bxxxxxx};

  assign c$ds_case_alt_9 = fwdIn_0[1:1] ? 1'b1 : 1'b0;

  assign c$ds_case_alt_selection_24 = result_14[10:0];

  assign c$ds_case_alt_10 = c$ds_case_alt_selection_24[10:10] ? {c$ds_app_arg_9,
                                                                 {bwd,   {1'b1,{fwdIn_0[9:2],   c$ds_app_arg_7,
                                                                                fwdIn_0[0:0]}}}} : {ds,   {bwd,
                                                                                                           {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_7 = done_0 ? c$ds_case_alt_11 : 1'd0;

  assign c$ds_case_alt_11 = fwdIn_0[1:1] ? 1'd1 : 1'd0;

  assign c$ds_app_arg_9 = bwd ? c$ds_case_alt_12 : ds;

  assign bwd = result_4[11:11];

  assign c$ds_case_alt_12 = done_0 ? c$ds_case_alt_13 : c$ds_case_alt_14;

  assign done_0 = i_0 == 6'd59;

  assign c$ds_case_alt_13 = fwdIn_0[1:1] ? {2'b00,6'd0} : {2'b01,6'bxxxxxx};

  assign c$ds_case_alt_14 = fwdIn_0[1:1] ? {2'b10,c$ds_app_arg_10} : {2'b00,c$ds_app_arg_10};

  assign fwdIn_0 = result_14[9:0];

  assign c$ds_app_arg_10 = i_0 + 6'd1;

  assign i_0 = ds[5:0];

  // register begin
  always @(posedge ethRxClk ) begin : ds_register
    if ( reset) begin
      ds <= {2'b00,6'd0};
    end else begin
      ds <= result_12[19:12];
    end
  end
  // register end

  assign a1_4 = result_17[121:0];

  assign result_selection_5 = result_17[122:0];

  assign result_13 = result_selection_5[122:122] ? {1'b1,{a1_4[121:114],
                                                          a1_4[113:113],   {a1_4[64:17],   a1_4[112:65],
                                                                            a1_4[16:1]},
                                                          a1_4[0:0]}} : {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign result_14 = result_15[11:0];

  always @(*) begin
    case(eta2_0[126:125])
      2'b00 : result_15 = c$ds_case_alt_19;
      2'b01 : result_15 = c$ds_case_alt_15;
      default : result_15 = {c$ds_app_arg_11,
                             {1'b0,   {1'b1,eta2_0[124:115]}}};
    endcase
  end

  assign c$ds_app_arg_11 = bwdIn_0 ? {2'b00,4'd0,{15 {8'b00000000}},1'b0} : eta2_0;

  assign c$ds_case_alt_15 = result_13[122:122] ? {c$ds_app_arg_13,
                                                  {bwdIn_0,   {1'b1,{ds8_0,   c$ds_app_arg_12,
                                                                     nextAborted_1}}}} : {eta2_0,   {bwdIn_0,
                                                                                                     {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_12 = newLast_0[1:1] ? c$ds_case_alt_16 : 1'd0;

  assign c$ds_case_alt_16 = newLast_0[0:0] ? 1'd0 : 1'd1;

  assign c$ds_app_arg_13 = bwdIn_0 ? c$ds_case_alt_17 : eta2_0;

  assign c$ds_case_alt_17 = newLast_0[1:1] ? c$ds_case_alt_18 : {2'b01,nextAborted_1,124'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds_case_alt_18 = newLast_0[0:0] ? {2'b10,{{1 {8'b00000000}},
                                                     1'd1,
                                                     nextAborted_1},115'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,4'd0,{15 {8'b00000000}},1'b0};

  assign newLast_0 = pkt_0[113:113] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign nextAborted_1 = eta2_0[124:124] | pkt_0[0:0];

  assign ds8_0 = pkt_0[121:114];

  assign c$ds_case_alt_19 = result_13[122:122] ? {c$ds_app_arg_14,
                                                  {1'b0,   {1'b1,{ds9_0[127:120],   1'd0,
                                                                  nextAborted_2}}}} : {eta2_0,   {bwdIn_0,
                                                                                                  {1'b0,10'bxxxxxxxxxx}}};

  assign c$ds_app_arg_14 = bwdIn_0 ? c$ds_case_alt_20 : eta2_0;

  assign c$ds_case_alt_sel_alt_t_31 = pkt_0[121:114];

  assign c$ds_case_alt_20 = (eta2_0[124:121] == 4'd13) ? {2'b01,nextAborted_2,124'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,eta2_0[124:121] + 4'd1,ds9_0[119:0],nextAborted_2};

  assign nextAborted_2 = eta2_0[0:0] | pkt_0[0:0];

  assign ds9_0 = c$ds9_app_arg_0;

  assign c$ds9_app_arg_selection_4 = eta2_0[124:121];

  always @(*) begin
    case(c$ds9_app_arg_selection_4)
      4'd0 : c$ds9_app_arg_0 = {({((result_16)),pkt_0[121:114]}),({1 {(8'd0)}})};
      default : c$ds9_app_arg_0 = {eta2_0[120:1],({1 {(8'd0)}})};
    endcase
  end

  assign g1 = pkt_0[112:65];

  assign g2 = pkt_0[64:17];

  assign g3 = pkt_0[16:1];

  // map begin
  genvar i_8;
  generate
  for (i_8=0; i_8 < 6; i_8 = i_8 + 1) begin : map_2
    wire [7:0] map_in_2;
    assign map_in_2 = g2[i_8*8+:8];
    wire [7:0] map_out_2;
    assign map_out_2 = map_in_2;


    assign c$app_arg_3[i_8*8+:8] = map_out_2;
  end
  endgenerate
  // map end

  // map begin
  genvar i_9;
  generate
  for (i_9=0; i_9 < 6; i_9 = i_9 + 1) begin : map_3
    wire [7:0] map_in_3;
    assign map_in_3 = g1[i_9*8+:8];
    wire [7:0] map_out_3;
    assign map_out_3 = map_in_3;


    assign c$app_arg_4[i_9*8+:8] = map_out_3;
  end
  endgenerate
  // map end

  assign result_16 = ((({((((c$app_arg_4)))),(({((((c$app_arg_3)))),(g3)}))})));

  assign pkt_0 = result_13[121:0];

  // register begin
  always @(posedge ethRxClk ) begin : eta2_0_register
    if ( reset) begin
      eta2_0 <= {2'b00,4'd0,{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000},1'b0};
    end else begin
      eta2_0 <= result_15[138:12];
    end
  end
  // register end

  assign bwdIn_0 = result_11[11:11];

  assign result_17 = {c$case_alt_0[11:11],
                      result_22[122:0]};

  assign result_18 = ds11_0 ? result_19 : ({247 {1'bx}});

  assign result_19 = pkt_1[1:1] ? {{2'b00,1'b0,{13 {8'b00000000}},4'd13,13'bxxxxxxxxxxxxx},
                                   {1'b1,{{1 {8'b00000000}},   1'd1,   result_20,
                                          nextAborted_4}}} : {{2'b01,nextAborted_4,result_20,9'bxxxxxxxxx},
                                                              {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign c$ds1_case_alt = back;

  assign result_20 = {(ds4[111:64]),
                      (c$ds1_case_alt[63:16]),
                      c$ds1_case_alt[15:0]};

  assign ds4 = ((c$mapOut));

  assign back = ds4[63:0];

  assign c$vec_4 = ds14_0;

  // map begin
  genvar i_10;
  generate
  for (i_10=0; i_10 < 14; i_10 = i_10 + 1) begin : map_4
    wire [7:0] map_in_4;
    assign map_in_4 = c$vec_4[i_10*8+:8];
    wire [7:0] map_out_4;
    assign map_out_4 = map_in_4;


    assign c$mapOut[i_10*8+:8] = map_out_4;
  end
  endgenerate
  // map end

  assign ds14_0 = combined;

  assign result_21 = pkt_1[1:1] ? {{2'b00,1'b0,{13 {8'b00000000}},4'd13,13'bxxxxxxxxxxxxx},
                                   {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}} : result_18;

  assign ds11_0 = eta5[16:13] == 4'd0;

  // register begin
  always @(posedge ethRxClk ) begin : eta5_register
    if ( reset) begin
      eta5 <= {2'b00,1'b0,{{8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}}},4'd13,13'bxxxxxxxxxxxxx};
    end else begin
      eta5 <= result_22[247:124];
    end
  end
  // register end

  always @(*) begin
    case(eta5[123:122])
      2'b00 : result_22 = c$ds2_case_alt_3;
      2'b01 : result_22 = c$ds2_case_alt;
      default : result_22 = {c$ds2_app_arg,   {1'b0,
                                               {1'b1,eta5[121:0]}}};
    endcase
  end

  assign c$ds2_app_arg = r2sAc_0 ? {2'b00,1'b0,{13 {8'b00000000}},4'd13,13'bxxxxxxxxxxxxx} : eta5;

  assign c$ds2_case_alt_selection_1 = c$case_alt_0[10:0];

  assign c$ds2_case_alt = c$ds2_case_alt_selection_1[10:10] ? {c$ds2_app_arg_1,
                                                               {r2sAc_0,   {1'b1,{ds10,   c$ds2_app_arg_0,
                                                                                  eta5[120:9],
                                                                                  nextAborted_3}}}} : {eta5,
                                                                                                       {r2sAc_0,
                                                                                                        {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds2_app_arg_0 = newLast_1[1:1] ? c$ds2_case_alt_0 : 1'd0;

  assign c$ds2_case_alt_0 = newLast_1[0:0] ? 1'd0 : 1'd1;

  assign c$ds2_app_arg_1 = r2sAc_0 ? c$ds2_case_alt_1 : eta5;

  assign c$ds2_case_alt_1 = newLast_1[1:1] ? c$ds2_case_alt_2 : {2'b01,nextAborted_3,eta5[120:9],9'bxxxxxxxxx};

  assign c$ds2_case_alt_2 = newLast_1[0:0] ? {2'b10,{{1 {8'b00000000}},
                                                     1'd1,   eta5[120:9],
                                                     nextAborted_3}} : {2'b00,1'b0,{13 {8'b00000000}},4'd13,13'bxxxxxxxxxxxxx};

  assign newLast_1 = pkt_1[1:1] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign nextAborted_3 = eta5[121:121] | pkt_1[0:0];

  assign ds10 = pkt_1[9:2];

  assign c$ds2_case_alt_selection_9 = c$case_alt_0[10:0];

  assign c$ds2_case_alt_3 = c$ds2_case_alt_selection_9[10:10] ? {c$ds2_app_arg_2,
                                                                 {readyOut,   fwdOut}} : {eta5,   {r2sAc_0,
                                                                                                   {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds2_app_arg_2 = readyOut ? result_23[246:123] : eta5;

  assign readyOut = c$readyOut_case_alt | r2sAc_0;

  assign r2sAc_0 = result_14[11:11];

  assign c$readyOut_case_alt = fwdOut[122:122] ? 1'b0 : 1'b1;

  assign fwdOut = result_23[122:0];

  assign result_23 = ds11_0 ? result_21 : c$ds10_case_alt;

  assign c$ds10_case_alt_sel_alt_f_0 = combined;

  assign c$ds10_case_alt = pkt_1[1:1] ? result_21 : {{2'b00,nextAborted_4,c$ds10_case_alt_sel_alt_f_0[103:0],eta5[16:13] - 4'd1,13'bxxxxxxxxxxxxx},
                                                     {1'b0,122'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign nextAborted_4 = eta5[121:121] | pkt_1[0:0];

  assign combined = {eta5[120:17],pkt_1[9:2]};

  assign pkt_1 = c$case_alt_0[9:0];

  assign bwd_0 = result_22[123:123];

  assign c$case_alt_0 = (reset) ? {1'b0,
                                   {1'b0,10'bxxxxxxxxxx}} : {bwd_0,   s2rAc_0};

  assign s2rAc_0 = result_34[10:0];

  assign result_24 = {inputVld & nibbleSelect,
                      {inputVld,   x_2,   x_1}};

  assign x_1 = nibbleSelect ? ds2[3:0] : ds2[7:4];

  assign x_selection_2 = result_1[10:0];

  assign x_2 = x_selection_2[10:10] ? a1_7[0:0] : 1'b0;

  assign ds2 = (c$ds2_app_arg_3);

  // register begin
  always @(posedge ethRxClk ) begin : nibbleSelect_register
    if ( reset) begin
      nibbleSelect <= 1'b0;
    end else if (inputVld) begin
      nibbleSelect <= (~ nibbleSelect);
    end
  end
  // register end

  assign inputVld_selection_1 = result_1[10:0];

  assign inputVld = inputVld_selection_1[10:10] ? 1'b1 : 1'b0;

  assign c$ds2_app_arg_selection_5 = result_1[10:0];

  assign c$vec_5 = a1_7[9:2];

  assign c$ds2_app_arg_3 = c$ds2_app_arg_selection_5[10:10] ? (c$vec_5[8-1 -: 8]) : ({8 {1'bx}});

  assign a1_7 = result_1[9:0];

  // register begin
  always @(posedge ethRxClk ) begin : c$ds_app_arg_15_register
    if ( reset) begin
      c$ds_app_arg_15 <= ({4 {1'bx}});
    end else begin
      c$ds_app_arg_15 <= nibble0;
    end
  end
  // register end

  // register begin
  always @(posedge ethRxClk ) begin : c$ds_app_arg_16_register
    if ( reset) begin
      c$ds_app_arg_16 <= 1'b0;
    end else begin
      c$ds_app_arg_16 <= dv0;
    end
  end
  // register end

  assign result_25 = (c$ds_app_arg_16 & (~ dv0)) ? 1'd1 : 1'd0;

  assign result_26 = dv0 ? {1'b1,{{nibble0,c$ds_app_arg_15},
                                  result_25,   ds3}} : {1'b0,10'bxxxxxxxxxx};

  assign c$case_alt_1 = result_26;

  assign dv0 = rxChannel[5:5];

  assign nibble0 = rxChannel[3:0];

  // register begin
  always @(posedge ethRxClk ) begin : ds3_register
    if ( reset) begin
      ds3 <= ({1 {1'bx}});
    end else begin
      ds3 <= rxChannel[4:4];
    end
  end
  // register end

  assign c$ds_app_arg_17 = result_35[10:10] ? 1'b0 : 1'b1;

  assign ds2_0 = {s2rAc_2,
                  c$ds_app_arg_17 | r2sAc_2};

  assign result_27 = {c$case_alt_2[11:11],
                      result_32[18:0]};

  assign result_28 = ds11_1 ? result_29 : ({81 {1'bx}});

  assign result_29 = pkt_2[1:1] ? {{2'b00,1'b0,{7 {8'b00000000}},3'd7},
                                   {1'b1,{{1 {8'b00000000}},   1'd1,   result_30,
                                          nextAborted_6}}} : {{2'b01,nextAborted_6,result_30,51'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
                                                              {1'b0,18'bxxxxxxxxxxxxxxxxxx}};

  assign c$vec_6 = ((((c$mapOut_0))));

  assign result_30 = c$vec_6[8-1:0];

  assign c$vec_7 = ds14_1;

  // map begin
  genvar i_11;
  generate
  for (i_11=0; i_11 < 8; i_11 = i_11 + 1) begin : map_5
    wire [7:0] map_in_5;
    assign map_in_5 = c$vec_7[i_11*8+:8];
    wire [7:0] map_out_5;
    assign map_out_5 = map_in_5;


    assign c$mapOut_0[i_11*8+:8] = map_out_5;
  end
  endgenerate
  // map end

  assign ds14_1 = combined_0;

  assign result_31 = pkt_2[1:1] ? {{2'b00,1'b0,{7 {8'b00000000}},3'd7},
                                   {1'b0,18'bxxxxxxxxxxxxxxxxxx}} : result_28;

  assign ds11_1 = eta5_0[2:0] == 3'd0;

  // register begin
  always @(posedge ethRxClk ) begin : eta5_0_register
    if ( reset) begin
      eta5_0 <= {2'b00,1'b0,{{8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}}},3'd7};
    end else begin
      eta5_0 <= result_32[81:20];
    end
  end
  // register end

  always @(*) begin
    case(eta5_0[61:60])
      2'b00 : result_32 = c$ds2_case_alt_8;
      2'b01 : result_32 = c$ds2_case_alt_4;
      default : result_32 = {c$ds2_app_arg_4,
                             {1'b0,   {1'b1,eta5_0[59:42]}}};
    endcase
  end

  assign c$ds2_app_arg_4 = r2sAc_1 ? {2'b00,1'b0,{7 {8'b00000000}},3'd7} : eta5_0;

  assign c$ds2_case_alt_selection_12 = c$case_alt_2[10:0];

  assign c$ds2_case_alt_4 = c$ds2_case_alt_selection_12[10:10] ? {c$ds2_app_arg_6,
                                                                  {r2sAc_1,   {1'b1,{ds10_0,   c$ds2_app_arg_5,
                                                                                     eta5_0[58:51],
                                                                                     nextAborted_5}}}} : {eta5_0,
                                                                                                          {r2sAc_1,
                                                                                                           {1'b0,18'bxxxxxxxxxxxxxxxxxx}}};

  assign c$ds2_app_arg_5 = newLast_2[1:1] ? c$ds2_case_alt_5 : 1'd0;

  assign c$ds2_case_alt_5 = newLast_2[0:0] ? 1'd0 : 1'd1;

  assign c$ds2_app_arg_6 = r2sAc_1 ? c$ds2_case_alt_6 : eta5_0;

  assign c$ds2_case_alt_6 = newLast_2[1:1] ? c$ds2_case_alt_7 : {2'b01,nextAborted_5,eta5_0[58:51],51'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds2_case_alt_7 = newLast_2[0:0] ? {2'b10,{{1 {8'b00000000}},
                                                     1'd1,   eta5_0[58:51],
                                                     nextAborted_5},42'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,1'b0,{7 {8'b00000000}},3'd7};

  assign newLast_2 = pkt_2[1:1] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign nextAborted_5 = eta5_0[59:59] | pkt_2[0:0];

  assign ds10_0 = pkt_2[9:2];

  assign c$ds2_case_alt_selection_20 = c$case_alt_2[10:0];

  assign c$ds2_case_alt_8 = c$ds2_case_alt_selection_20[10:10] ? {c$ds2_app_arg_7,
                                                                  {readyOut_0,   fwdOut_0}} : {eta5_0,
                                                                                               {r2sAc_1,
                                                                                                {1'b0,18'bxxxxxxxxxxxxxxxxxx}}};

  assign c$ds2_app_arg_7 = readyOut_0 ? result_33[80:19] : eta5_0;

  assign readyOut_0 = c$readyOut_case_alt_0 | r2sAc_1;

  assign r2sAc_1 = ds2_0[0:0];

  assign c$readyOut_case_alt_0 = fwdOut_0[18:18] ? 1'b0 : 1'b1;

  assign fwdOut_0 = result_33[18:0];

  assign result_33 = ds11_1 ? result_31 : c$ds10_case_alt_0;

  assign c$ds10_case_alt_sel_alt_f_4 = combined_0;

  assign c$ds10_case_alt_0 = pkt_2[1:1] ? result_31 : {{2'b00,nextAborted_6,c$ds10_case_alt_sel_alt_f_4[55:0],eta5_0[2:0] - 3'd1},
                                                       {1'b0,18'bxxxxxxxxxxxxxxxxxx}};

  assign nextAborted_6 = eta5_0[59:59] | pkt_2[0:0];

  assign combined_0 = {eta5_0[58:3],pkt_2[9:2]};

  assign pkt_2 = c$case_alt_2[9:0];

  assign bwd_1 = result_32[19:19];

  assign c$case_alt_2 = (reset) ? {1'b0,
                                   {1'b0,10'bxxxxxxxxxx}} : {bwd_1,   s2rAc_1};

  assign s2rAc_1 = ds2_0[11:1];

  assign result_34 = {result_27[19:19],
                      result_35};

  assign x_3 = result_27[17:0];

  assign c$case_alt_selection_4 = x_3[8:1];

  always @(*) begin
    case(c$case_alt_selection_4)
      8'b11010101 : c$case_alt_3 = {1'b1,{x_3[17:10],
                                          x_3[9:9],   x_3[0:0]}};
      default : c$case_alt_3 = {1'b0,10'bxxxxxxxxxx};
    endcase
  end

  assign result_selection_25 = result_27[18:0];

  assign result_35 = result_selection_25[18:18] ? c$case_alt_3 : {1'b0,10'bxxxxxxxxxx};

  assign s2rAc_2 = c$case_alt_1;

  assign r2sAc_2 = result_17[123:123];

  assign result_36 = result_24[5:0];

  assign result = result_36;

  assign tx_en = result[5:5];

  assign tx_err = result[4:4];

  assign tx_data = result[3:0];


endmodule
