/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  ethRxClk // clock
    , input  ethTxClk // clock
    , input  rstN // reset
    , input  rxDv
    , input  rxErr
    , input [3:0] rxData

      // Outputs
    , output wire  txEn
    , output wire  txErr
    , output wire [3:0] txData
    );
  wire  c$bindCsr;
  wire  c$app_arg;
  wire [11:0] result_0;
  reg [19:0] c$ds1_case_alt;
  wire [19:0] result_1;
  wire [19:0] result_2;
  wire [63:0] c$mapOut;
  reg [63:0] c$mapOut_app_arg;
  reg [69:0] eta6;
  reg [89:0] result_3;
  wire  c$ds2_app_arg;
  wire [69:0] c$ds2_app_arg_1;
  wire [89:0] c$ds2_case_alt_0;
  wire [7:0] result_4;
  wire [0:0] c$ds2_app_arg_2;
  wire [0:0] c$ds2_case_alt_1;
  wire  c$ds2_app_arg_3;
  wire  c$ds2_case_alt_2;
  wire [69:0] c$ds2_app_arg_4;
  wire [69:0] c$ds2_case_alt_3;
  wire [69:0] c$ds2_case_alt_4;
  wire [1:0] newLast;
  wire  nextAborted;
  wire [7:0] ds11;
  wire [89:0] c$ds2_case_alt_5;
  wire  r2sAc;
  reg  c$ds2_app_arg_5;
  wire [69:0] result_5;
  wire [69:0] c$nextSt_case_alt;
  wire [69:0] c$case_alt;
  wire [69:0] result_6;
  wire  nextAborted_0;
  wire [63:0] nextParseBuf;
  wire [2:0] nextCounter;
  wire  rstLow;
  wire  bwd;
  wire [11:0] c$case_alt_0;
  wire  ds13;
  wire [10:0] c$app_arg_0;
  wire [11:0] result_7;
  wire  r2sAc_0;
  wire [18:0] wild1;
  wire [17:0] inPkt;
  wire [17:0] a1_0;
  wire [10:0] s2rAc;
  wire [20:0] result_8;
  wire [19:0] c$ds8_app_arg;
  wire [20:0] c$ds8_app_arg_0;
  wire [20:0] c$ds8_case_alt;
  wire [20:0] c$ds8_case_alt_0;
  wire  c$ds8_case_scrut;
  wire  r2sAc_1;
  wire [1:0] c$ds8_app_arg_1;
  wire  c$ds8_app_arg_2;
  wire  c$ds8_app_arg_3;
  wire [0:0] c$ds8_app_arg_4;
  wire  nextFlush;
  wire  c$nextFlush_app_arg;
  wire [15:0] c$ds8_app_arg_5;
  wire  rstLow_0;
  wire [11:0] c$case_alt_1;
  wire [10:0] s2rAc_0;
  reg [20:0] st;
  wire [19:0] result_9;
  wire [20:0] result_10;
  wire  empty;
  wire [20:0] ds1;
  wire [19:0] fwdIn;
  wire  bwdIn;
  wire [19:0] f1;
  wire [20:0] result_11;
  wire [19:0] s2rAc_1;
  wire  ready;
  wire [41:0] c$case_alt_2;
  wire [18:0] c$case_alt_3;
  wire [20:0] c$app_arg_1;
  wire  c$outValid_case_alt;
  wire [18:0] cache;
  wire  validated;
  wire  r2sAc_2;
  wire  result_12;
  wire  result_13;
  wire [1:0] xs;
  reg [0:0] i1;
  wire [31:0] c$crcState_app_arg;
  reg [31:0] crcState;
  wire [15:0] c$case_alt_4;
  wire [15:0] x;
  wire [31:0] c$app_arg_2;
  wire [31:0] result_14;
  wire [16:0] ds10;
  wire [16:0] a1_1;
  reg  c$app_arg_3;
  wire  c$app_arg_4;
  wire [17:0] c$ds3_app_arg;
  wire [0:0] c$ds3_app_arg_0;
  wire [0:0] v;
  reg  c$ds3_app_arg_1;
  wire  c$ds3_case_alt;
  wire [18:0] fwdInX;
  wire [18:0] a1_2;
  wire  transferOccured;
  wire  c$transferOccured_app_arg;
  wire [19:0] fwdIn_0;
  wire  rstLow_1;
  wire [20:0] c$case_alt_5;
  reg [20:0] c$ds3_app_arg_2;
  wire [132:0] result_15;
  wire [111:0] c$mapOut_0;
  reg [111:0] c$mapOut_app_arg_0;
  reg [118:0] eta6_0;
  reg [251:0] result_16;
  wire  c$ds2_app_arg_6;
  wire [0:0] c$ds2_app_arg_7;
  wire [0:0] c$ds2_case_alt_6;
  wire [118:0] c$ds2_app_arg_8;
  wire [251:0] c$ds2_case_alt_7;
  wire [1:0] c$ds2_app_arg_9;
  wire [1:0] c$ds2_case_alt_8;
  wire [0:0] x1_0;
  wire [63:0] c$ds1_case_alt_0;
  wire [111:0] result_17;
  wire [111:0] ds4;
  wire [63:0] back;
  wire  c$ds2_app_arg_10;
  wire  c$ds2_case_alt_9;
  wire [118:0] c$ds2_app_arg_11;
  wire [118:0] c$ds2_case_alt_10;
  wire [118:0] c$ds2_case_alt_11;
  wire [0:0] idx_0;
  wire [2:0] newLast_0;
  wire [0:0] a1_3;
  wire  nextAborted_1;
  wire [15:0] ds11_0;
  wire [251:0] c$ds2_case_alt_12;
  wire  r2sAc_3;
  reg  c$ds2_app_arg_12;
  wire [118:0] result_18;
  wire [118:0] c$nextSt_case_alt_0;
  wire [118:0] c$case_alt_6;
  wire [118:0] result_19;
  wire  nextAborted_2;
  wire [111:0] nextParseBuf_0;
  wire [2:0] nextCounter_0;
  wire  rstLow_2;
  wire  bwd_0;
  wire [20:0] c$case_alt_7;
  wire [19:0] s2rAc_2;
  wire  ds13_0;
  wire [132:0] result_20;
  wire [132:0] c$ds17_case_alt;
  wire  result_21;
  wire  c$case_alt_8;
  wire [5:0] c$app_arg_5;
  wire  c$case_alt_9;
  wire [5:0] c$app_arg_6;
  wire [130:0] inPkt_0;
  wire [131:0] wild1_0;
  reg [38:0] c$ds_app_arg;
  wire [132:0] c$case_alt_10;
  wire  bwdIn_0;
  wire [170:0] c$case_alt_11;
  reg [15:0] c$app_arg_7;
  wire [15:0] a;
  wire [16:0] summed;
  wire [15:0] result_22;
  wire [15:0] c$app_arg_8;
  reg [15:0] dataOut0;
  wire [38:0] c$app_arg_9;
  wire [1:0] c$case_alt_12;
  reg [1:0] c$case_alt_13;
  wire [1:0] c$case_alt_14;
  reg [1:0] c$case_alt_15;
  wire [1:0] c$case_alt_16;
  wire [3:0] c$case_alt_17;
  reg [3:0] c$case_alt_18;
  wire [3:0] c$case_alt_19;
  wire [3:0] c$nextFsm_case_alt;
  reg [3:0] c$nextFsm_case_alt_0;
  wire [3:0] result_23;
  wire signed [63:0] \a# ;
  wire [15:0] c$dataOut0_case_alt;
  wire [15:0] c$dataOut0_case_alt_0;
  wire [47:0] dShift2;
  reg  result_24;
  wire  errNow;
  wire  c$foldOut;
  wire [1:0] c$zipWithOut;
  wire [15:0] dShift1;
  wire [130:0] ipv;
  reg [17:0] c$zipWithOut_app_arg;
  wire [17:0] c$mapOut_1;
  wire [15:0] c$mapOut_app_arg_1;
  wire  stateCntZero;
  wire [264:0] result_25;
  wire [264:0] ds;
  wire [264:0] result_26;
  wire [263:0] c$ds_app_arg_0;
  wire  c$ds_app_arg_1;
  wire signed [63:0] c$ds_app_arg_2;
  wire [0:0] i;
  wire [1:0] c$ds_case_scrut;
  wire [5:0] ws;
  wire [3:0] c$ws_app_arg;
  wire [5:0] c$ws_app_arg_0;
  wire [130:0] x_0;
  wire [133:0] result_27;
  wire [1:0] c$ds1_app_arg;
  wire  c$ds1_app_arg_0;
  wire  c$ds1_case_alt_1;
  wire [0:0] result_28;
  wire [0:0] c$ds1_case_alt_2;
  wire  first;
  wire [0:0] c$ds1_case_alt_3;
  wire [131:0] fwd;
  wire signed [63:0] c$fwd_app_arg;
  wire [0:0] c$ds1_case_alt_4;
  wire [1:0] z;
  wire [0:0] result_29;
  wire [0:0] i_0;
  reg [1:0] ds2;
  reg [6:0] c$ds1_app_arg_1;
  reg [15:0] c$ds1_app_arg_2;
  wire [132:0] result_30;
  wire [146:0] c$case_alt_20;
  wire [6:0] nextCnt;
  wire [131:0] c$case_alt_21;
  wire [1:0] c$app_arg_10;
  wire  lastWord;
  wire  c$case_alt_22;
  wire [7:0] z_0;
  wire [6:0] result_31;
  wire  c$nextCnt_case_alt;
  wire [130:0] fwdIn_1;
  wire [131:0] fwdIn_2;
  wire  bwdIn_1;
  wire [132:0] result_32;
  wire [131:0] eth_Fwd;
  wire  \final:stmt_Bwd ;
  wire  eth_Bwd;
  wire [131:0] \final:stmt_Fwd ;
  wire [20:0] result_33;
  reg [154:0] result_34;
  wire [133:0] c$ds_app_arg_3;
  wire [154:0] c$ds_case_alt;
  wire [1:0] c$ds_app_arg_4;
  wire [1:0] c$ds_case_alt_0;
  wire [0:0] x1_1;
  wire [133:0] c$ds_app_arg_5;
  wire [133:0] c$ds_case_alt_1;
  wire [133:0] c$ds_case_alt_2;
  wire [0:0] idx_1;
  wire [2:0] newLast_1;
  wire [1:0] c$newLast_app_arg;
  wire [0:0] a1_4;
  wire  nextAborted_3;
  wire [15:0] ds8;
  wire [154:0] c$ds_case_alt_3;
  wire [133:0] c$ds_app_arg_6;
  wire [133:0] c$ds_case_alt_4;
  wire  nextAborted_4;
  wire [143:0] ds9;
  reg [143:0] c$ds9_app_arg;
  wire [47:0] g1;
  wire [47:0] g2;
  wire [15:0] g3;
  wire [47:0] c$app_arg_11;
  wire [47:0] c$app_arg_12;
  wire [111:0] result_35;
  wire [130:0] pkt;
  reg [133:0] eta2;
  wire  bwdIn_2;
  wire [20:0] result_36;
  reg [27:0] result_37;
  wire [1:0] c$ds_app_arg_7;
  wire [6:0] c$ds_app_arg_8;
  wire [6:0] c$ds_case_alt_5;
  wire  done;
  wire [4:0] i_1;
  wire [27:0] c$ds_case_alt_6;
  wire [6:0] c$ds_app_arg_9;
  wire  c$ds_case_alt_7;
  wire [27:0] c$ds_case_alt_8;
  wire [1:0] c$ds_app_arg_10;
  wire [1:0] c$ds_case_alt_9;
  wire [0:0] c$ds_app_arg_11;
  wire [0:0] a1_5;
  wire [6:0] c$ds_app_arg_12;
  wire  bwd_1;
  wire [6:0] c$ds_case_alt_10;
  wire  done_0;
  wire [6:0] c$ds_case_alt_11;
  wire [6:0] c$ds_case_alt_12;
  wire [18:0] fwdIn_3;
  wire [4:0] c$ds_app_arg_13;
  wire [4:0] i_2;
  reg [6:0] ds_0;
  wire [20:0] result_38;
  wire [76:0] result_39;
  wire [76:0] c$ds8_case_alt_1;
  wire [18:0] c$ds8_app_arg_6;
  wire [55:0] c$ds8_app_arg_7;
  wire [55:0] c$ds8_case_alt_2;
  wire [55:0] c$ds8_case_alt_3;
  wire [1:0] x_1;
  wire [2:0] insertCrc;
  wire [47:0] ds14;
  wire [47:0] c$ds14_app_arg;
  wire [95:0] c$app_arg_13;
  wire [47:0] \xs' ;
  wire [7:0] x1_2;
  wire [15:0] x1_3;
  wire [47:0] result_40;
  wire [0:0] c$ds8_app_arg_8;
  wire [0:0] a1_6;
  wire [18:0] cache_0;
  wire [19:0] fwdIn_4;
  wire [1:0] c$ds8_app_arg_9;
  wire [55:0] c$ds8_app_arg_10;
  wire  r2sAc_4;
  wire [31:0] result_41;
  wire [31:0] result_42;
  wire [31:0] c$app_arg_14;
  wire [31:0] result_43;
  wire [31:0] c$app_arg_15;
  reg [31:0] crcState_0;
  reg [31:0] c$crcState_case_alt;
  wire [15:0] c$case_alt_23;
  wire [15:0] x_2;
  wire [31:0] c$app_arg_16;
  wire [31:0] result_44;
  wire [7:0] x_3;
  wire [31:0] c$app_arg_17;
  wire [31:0] result_45;
  wire [31:0] c$crcState_app_arg_0;
  wire  c$crcState_app_arg_1;
  wire [16:0] ds11_1;
  wire [16:0] a1_7;
  wire [17:0] c$x_app_arg;
  wire [0:0] c$x_app_arg_0;
  wire [0:0] v_0;
  reg  c$x_app_arg_1;
  wire  c$x_case_alt;
  wire [18:0] fwdInX_0;
  wire [18:0] a1_8;
  wire  transferOccured_0;
  wire  ready_0;
  wire  c$transferOccured_app_arg_0;
  wire  rstLow_3;
  wire [20:0] c$case_alt_24;
  wire [19:0] s2rAc_3;
  wire [55:0] c$ds8_case_alt_4;
  wire  finished;
  wire [47:0] ds15;
  reg [55:0] ds6;
  wire [20:0] result_46;
  reg [105:0] result_47;
  wire [84:0] c$ds_app_arg_14;
  wire [105:0] c$ds_case_alt_13;
  wire [1:0] c$ds_app_arg_15;
  wire [1:0] c$ds_case_alt_14;
  wire [0:0] x1_4;
  wire [84:0] c$ds_app_arg_16;
  wire [84:0] c$ds_case_alt_15;
  wire [84:0] c$ds_case_alt_16;
  wire [0:0] idx_2;
  wire [2:0] newLast_2;
  wire [1:0] c$newLast_app_arg_0;
  wire [0:0] a1_9;
  wire  nextAborted_5;
  wire [15:0] ds8_0;
  wire [105:0] c$ds_case_alt_17;
  wire [84:0] c$ds_app_arg_17;
  wire [84:0] c$ds_case_alt_18;
  wire  nextAborted_6;
  wire [95:0] ds9_0;
  reg [95:0] c$ds9_app_arg_0;
  wire [18:0] pkt_0;
  reg [84:0] eta2_0;
  wire  bwdIn_3;
  wire [11:0] result_48;
  wire [10:0] c$ds8_app_arg_11;
  wire [0:0] c$ds8_app_arg_12;
  wire [19:0] result_49;
  wire [19:0] c$ds8_case_alt_5;
  wire  outReady;
  wire  c$outReady_app_arg;
  wire  aborted;
  wire [15:0] vs;
  wire  c$ds8_app_arg_13;
  wire [1:0] c$ds8_app_arg_14;
  wire [0:0] x_4;
  wire [1:0] lastIdx;
  wire [18:0] inp;
  wire [17:0] ds11_2;
  wire  r2sAc_5;
  wire  c$ds11_app_arg;
  reg [19:0] st_0;
  wire  rstLow_4;
  wire [20:0] c$case_alt_25;
  wire [19:0] s2rAc_4;
  wire [4:0] c$ds_app_arg_18;
  wire [4:0] c$ds_case_alt_19;
  wire [16:0] c$ds_case_alt_20;
  wire [16:0] result_50;
  wire [11:0] result_51;
  reg [4:0] ds1_0;
  wire [9:0] inp_0;
  wire  r2sAc_6;
  wire [131:0] c$ds23_app_arg;
  wire [130:0] a1_10;
  reg [3:0] c$ds_app_arg_19;
  reg  c$ds_app_arg_20;
  wire [0:0] result_52;
  reg  c$ds3_app_arg_3;
  wire [10:0] result_53;
  wire [10:0] c$case_alt_26;
  reg  dv0;
  reg [3:0] nibble0;
  reg  ds3;
  wire [6:0] result_54;
  reg [3:0] c$app_arg_18;
  wire [3:0] c$app_arg_19;
  wire [7:0] ds2_0;
  reg  c$app_arg_20;
  wire  c$app_arg_21;
  reg  c$app_arg_22;
  reg  nibbleSelect;
  wire  inputVld;
  wire [7:0] c$ds2_app_arg_13;
  wire [9:0] a1_11;
  wire [5:0] result_55;
  wire [5:0] rxChannel;
  wire  c$bindCsr_fun_arg;
  wire [7:0] c$ds1_case_alt_selection_1;
  wire [63:0] c$mapOut_app_arg_sel_alt_0;
  wire [63:0] c$mapOut_app_arg_sel_alt_2;
  wire [10:0] c$ds2_app_arg_selection_1;
  wire [10:0] c$ds2_case_alt_selection_5;
  wire [63:0] c$vec;
  wire [10:0] c$ds2_case_alt_selection_15;
  wire [71:0] nextParseBuf_projection;
  wire [7:0] fwdBuf_projection;
  wire [18:0] c$app_arg_selection_1;
  wire [10:0] c$ds8_app_arg_selection_3;
  wire [1:0] c$ds8_app_arg_selection_10;
  wire [0:0] c$i_10;
  wire [7:0] c$vec_0;
  wire [15:0] c$vec_1;
  wire  ds1_fun_arg;
  wire [19:0] c$case_alt_selection_4;
  wire [1:0] c$case_alt_selection_7;
  wire [1:0] c$outValid_case_alt_selection_1;
  wire [63:0] c$vec1;
  wire [63:0] c$vec2;
  wire [15:0] x_projection;
  wire [1535:0] c$vec_2;
  wire [1:0] c$ds3_app_arg_selection_2;
  wire [1:0] c$ds3_case_alt_selection_1;
  wire [111:0] c$mapOut_app_arg_sel_alt_4;
  wire [111:0] c$mapOut_app_arg_sel_alt_6;
  wire [19:0] c$ds2_app_arg_selection_12;
  wire [19:0] c$ds2_app_arg_selection_15;
  wire [1:0] c$ds2_case_alt_selection_20;
  wire [19:0] c$ds2_case_alt_selection_23;
  wire [1:0] c$ds2_case_alt_selection_26;
  wire [1:0] c$ds2_case_alt_selection_29;
  wire [1:0] c$ds2_case_alt_selection_33;
  wire [1:0] newLast_selection_7;
  wire [19:0] c$ds2_case_alt_selection_36;
  wire [1:0] c$nextSt_case_alt_selection_7;
  wire [1:0] result_selection_13;
  wire [127:0] nextParseBuf_projection_6;
  wire [15:0] fwdBuf_projection_4;
  wire [47:0] c$vec1_0;
  wire [47:0] c$vec2_0;
  wire [47:0] c$vec1_1;
  wire [47:0] c$vec2_1;
  wire [1:0] c$vec_3;
  wire [0:0] c$vec_4;
  wire [131:0] c$case_alt_selection_res;
  wire [263:0] c$vec_5;
  wire [131:0] c$vec_6;
  wire [3:0] c$app_arg_selection_6;
  wire [16:0] c$bv;
  wire [0:0] c$bv_0;
  wire [3:0] dataOut0_selection_1;
  wire [1:0] c$vec_7;
  wire [0:0] c$vec_8;
  wire [1:0] c$case_alt_selection_14;
  wire [3:0] c$case_alt_selection_17;
  wire [1:0] c$case_alt_selection_22;
  wire [3:0] c$case_alt_selection_25;
  wire [1:0] c$nextFsm_case_alt_selection_1;
  wire [3:0] c$nextFsm_case_alt_selection_4;
  wire signed [63:0] c$tte_rhs;
  wire [3:0] c$dtt_rhs_1;
  wire [3:0] result_selection_17;
  wire [263:0] c$vec_9;
  wire [131:0] c$vec_10;
  wire [131:0] ipv_projection;
  wire [3:0] c$zipWithOut_app_arg_selection_1;
  wire [31:0] c$mapOut_app_arg_sel_alt_t_res;
  wire [31:0] c$mapOut_app_arg_sel_alt_t_res_res;
  wire [31:0] c$vec_11;
  wire [31:0] c$vec_12;
  wire [31:0] c$mapOut_app_arg_sel_alt_f_res;
  wire [31:0] c$mapOut_app_arg_sel_alt_f_res_res;
  wire [31:0] c$vec_13;
  wire [31:0] c$vec_14;
  wire [263:0] c$vec_15;
  wire [1:0] c$vecFlat;
  wire [1:0] c$vec1_2;
  wire [3:0] c$vec2_2;
  wire [1:0] c$vec_16;
  wire [1:0] c$ds1_case_alt_selection_5;
  wire [1:0] c$ds1_case_alt_selection_10;
  wire [263:0] c$vecFlat_0;
  wire [1:0] c$bv_1;
  wire [6:0] c$i_104;
  wire [1:0] c$case_alt_selection_31;
  wire [1:0] c$case_alt_selection_34;
  wire [7:0] c$bv_2;
  wire [1:0] c$nextCnt_case_alt_selection_1;
  wire [263:0] c$vec_17;
  wire [1:0] c$vec_18;
  wire [1:0] c$ds_case_alt_selection_2;
  wire [1:0] c$ds_case_alt_selection_6;
  wire [1:0] newLast_selection_10;
  wire [15:0] c$ds_case_alt_sel_alt_t_7;
  wire [2:0] c$ds9_app_arg_selection_1;
  wire [19:0] c$ds_case_alt_selection_12;
  wire [1:0] c$ds_case_alt_selection_15;
  wire [19:0] c$ds_case_alt_selection_18;
  wire [1:0] c$ds_case_alt_selection_21;
  wire [1:0] c$ds_case_alt_selection_25;
  wire [1:0] c$ds_case_alt_selection_28;
  wire [19:0] c$ds8_case_alt_selection_3;
  wire [1:0] insertCrc_selection_1;
  wire [1:0] c$ds14_app_arg_selection_1;
  wire [95:0] c$vec_19;
  wire [15:0] x1_projection_5;
  wire [15:0] x1_projection_6;
  wire [1:0] c$ds8_app_arg_selection_16;
  wire [1:0] c$bv_3;
  wire [31:0] c$vec_20;
  wire [31:0] c$vec_21;
  wire signed [63:0] c$crcState_case_alt_selection_1;
  wire [0:0] c$i_171;
  wire signed [63:0] c$crcState_case_alt_selection_0;
  wire [15:0] x_projection_5;
  wire [1535:0] c$vec_22;
  wire [15:0] x_projection_6;
  wire [1279:0] c$vec_23;
  wire [1:0] c$x_app_arg_selection_2;
  wire [1:0] c$x_case_alt_selection_1;
  wire [19:0] fwdInX_selection_2;
  wire [19:0] c$transferOccured_app_arg_selection_2;
  wire [19:0] c$ds_case_alt_selection_31;
  wire [1:0] c$ds_case_alt_selection_34;
  wire [1:0] c$ds_case_alt_selection_38;
  wire [1:0] newLast_selection_13;
  wire [19:0] c$ds_case_alt_selection_41;
  wire [15:0] c$ds_case_alt_sel_alt_t_28;
  wire [1:0] c$ds9_app_arg_selection_4;
  wire [63:0] c$ds9_app_arg_sel_alt_res;
  wire [63:0] c$vec_24;
  wire [15:0] c$vec_25;
  wire [19:0] result_selection_29;
  wire [23:0] ds11_sel_alt_t_1;
  wire [10:0] c$ds_case_alt_selection_47;
  wire [131:0] c$ds23_app_arg_selection_1;
  wire [10:0] c$app_arg_selection_12;
  wire [10:0] inputVld_selection_1;
  wire [10:0] c$ds2_app_arg_selection_23;
  wire [7:0] c$vec_26;
  wire [5:0] result;

  assign rxChannel = {rxDv,   rxErr,   rxData};

  assign c$bindCsr_fun_arg = ((rstN));

  Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_resetSynchronizer_0 Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_resetSynchronizer_0_c$bindCsr
    ( .result (c$bindCsr)
    , .eta (ethTxClk)
    , .eta1 (c$bindCsr_fun_arg) );

  Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_resetSynchronizer Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_resetSynchronizer_c$app_arg
    ( .result (c$app_arg)
    , .eta (ethRxClk)
    , .eta1 (rstN) );

  assign result_0 = {result_7[11:11],
                     result_51[10:0]};

  assign c$ds1_case_alt_selection_1 = inPkt[8:1];

  always @(*) begin
    case(c$ds1_case_alt_selection_1)
      8'b11010101 : c$ds1_case_alt = {r2sAc_0,
                                      wild1};
      default : c$ds1_case_alt = {1'b1,
                                  {1'b0,18'bxxxxxxxxxxxxxxxxxx}};
    endcase
  end

  assign result_1 = wild1[18:18] ? c$ds1_case_alt : {r2sAc_0,
                                                     {1'b0,18'bxxxxxxxxxxxxxxxxxx}};

  assign result_2 = {c$case_alt_0[11:11],
                     result_3[18:0]};

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 8; i_3 = i_3 + 1) begin : map
    wire [7:0] map_in;
    assign map_in = c$mapOut_app_arg[i_3*8+:8];
    wire [7:0] map_out;
    assign map_out = map_in;


    assign c$mapOut[i_3*8+:8] = map_out;
  end
  endgenerate
  // map end

  assign c$mapOut_app_arg_sel_alt_0 = eta6[66:3];

  assign c$mapOut_app_arg_sel_alt_2 = eta6[66:3];

  always @(*) begin
    case(eta6[69:68])
      2'b01 : c$mapOut_app_arg = c$mapOut_app_arg_sel_alt_0;
      default : c$mapOut_app_arg = c$mapOut_app_arg_sel_alt_2;
    endcase
  end

  // register begin
  always @(posedge ethRxClk ) begin : eta6_register
    if ( ! c$app_arg) begin
      eta6 <= {2'b00,1'b0,{{8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}}},3'd7};
    end else begin
      eta6 <= result_3[89:20];
    end
  end
  // register end

  always @(*) begin
    case(eta6[69:68])
      2'b00 : result_3 = c$ds2_case_alt_5;
      2'b01 : result_3 = c$ds2_case_alt_0;
      default : result_3 = {c$ds2_app_arg_1,
                            {r2sAc,   {1'b1,{{1 {8'b00000000}},   1'd1,
                                             result_4,   eta6[67:67] | c$ds2_app_arg}}}};
    endcase
  end

  assign c$ds2_app_arg_selection_1 = c$case_alt_0[10:0];

  assign c$ds2_app_arg = c$ds2_app_arg_selection_1[10:10] ? c$case_alt_0[0:0] : ({1 {1'bx}});

  assign c$ds2_app_arg_1 = r2sAc ? {2'b00,1'b0,eta6[66:3],3'd7} : eta6;

  assign c$ds2_case_alt_selection_5 = c$case_alt_0[10:0];

  assign c$ds2_case_alt_0 = c$ds2_case_alt_selection_5[10:10] ? {c$ds2_app_arg_4,
                                                                 {c$ds2_app_arg_3,   {1'b1,{ds11,
                                                                                            c$ds2_app_arg_2,
                                                                                            result_4,
                                                                                            nextAborted}}}} : {eta6,
                                                                                                               {r2sAc,
                                                                                                                {1'b0,18'bxxxxxxxxxxxxxxxxxx}}};

  assign c$vec = ((((c$mapOut))));

  assign result_4 = c$vec[8-1:0];

  assign c$ds2_app_arg_2 = newLast[1:1] ? c$ds2_case_alt_1 : 1'd0;

  assign c$ds2_case_alt_1 = newLast[0:0] ? 1'd0 : 1'd1;

  assign c$ds2_app_arg_3 = newLast[1:1] ? c$ds2_case_alt_2 : r2sAc;

  assign c$ds2_case_alt_2 = newLast[0:0] ? 1'b0 : r2sAc;

  assign c$ds2_app_arg_4 = r2sAc ? c$ds2_case_alt_3 : eta6;

  assign c$ds2_case_alt_3 = newLast[1:1] ? c$ds2_case_alt_4 : {2'b01,nextAborted,eta6[66:3],eta6[2:0]};

  assign c$ds2_case_alt_4 = newLast[0:0] ? {2'b10,nextAborted,eta6[66:3],eta6[2:0]} : {2'b00,1'b0,eta6[66:3],3'd7};

  assign newLast = c$case_alt_0[1:1] ? {1'b1,1'd0} : {1'b0,1'bx};

  assign nextAborted = eta6[67:67] | c$case_alt_0[0:0];

  assign ds11 = c$case_alt_0[9:2];

  assign c$ds2_case_alt_selection_15 = c$case_alt_0[10:0];

  assign c$ds2_case_alt_5 = c$ds2_case_alt_selection_15[10:10] ? {result_5,
                                                                  {c$ds2_app_arg_5,
                                                                   {1'b0,18'bxxxxxxxxxxxxxxxxxx}}} : {eta6,
                                                                                                      {r2sAc,
                                                                                                       {1'b0,18'bxxxxxxxxxxxxxxxxxx}}};

  assign r2sAc = result_1[19:19];

  always @(*) begin
    case(result_5[69:68])
      2'b10 : c$ds2_app_arg_5 = 1'b0;
      default : c$ds2_app_arg_5 = 1'b1;
    endcase
  end

  assign result_5 = ds13 ? result_6 : c$nextSt_case_alt;

  assign c$nextSt_case_alt = c$case_alt_0[1:1] ? result_6 : {2'b00,nextAborted_0,nextParseBuf,nextCounter};

  assign c$case_alt = ds13 ? {2'b01,nextAborted_0,nextParseBuf,nextCounter} : ({70 {1'bx}});

  assign result_6 = c$case_alt_0[1:1] ? {2'b00,1'b0,nextParseBuf,3'd7} : c$case_alt;

  assign nextAborted_0 = eta6[67:67] | c$case_alt_0[0:0];

  assign nextParseBuf_projection = ({eta6[66:3],c$case_alt_0[9:2]});

  assign nextParseBuf = nextParseBuf_projection[63:0];

  assign fwdBuf_projection = c$case_alt_0[9:2];

  assign nextCounter = eta6[2:0] - 3'd1;

  assign rstLow = ~ (c$app_arg);

  assign bwd = result_3[19:19];

  assign c$case_alt_0 = rstLow ? {1'b0,
                                  {1'b0,10'bxxxxxxxxxx}} : {bwd,   s2rAc};

  assign ds13 = eta6[2:0] == 3'd0;

  assign c$app_arg_selection_1 = result_1[18:0];

  assign c$app_arg_0 = c$app_arg_selection_1[18:18] ? {1'b1,{a1_0[17:10],
                                                             a1_0[9:9],
                                                             a1_0[0:0]}} : {1'b0,10'bxxxxxxxxxx};

  assign result_7 = {result_2[19:19],
                     c$app_arg_0};

  assign r2sAc_0 = result_8[20:20];

  assign wild1 = result_2[18:0];

  assign inPkt = wild1[17:0];

  assign a1_0 = result_1[17:0];

  assign s2rAc = c$case_alt_26;

  assign result_8 = {c$case_alt_1[11:11],
                     c$ds8_app_arg};

  assign c$ds8_app_arg = st[3:3] ? {1'b1,{st[20:5],
                                          st[1:0],
                                          st[2:2]}} : {1'b0,19'bxxxxxxxxxxxxxxxxxxx};

  assign c$ds8_app_arg_selection_3 = c$case_alt_1[10:0];

  assign c$ds8_app_arg_0 = c$ds8_app_arg_selection_3[10:10] ? c$ds8_case_alt_0 : c$ds8_case_alt;

  assign c$ds8_case_alt = c$ds8_case_scrut ? {st[20:5],
                                              st[4:4],   1'b0,   c$ds8_app_arg_2,
                                              {1'b0,1'bx}} : st;

  assign c$ds8_case_alt_0 = c$ds8_case_scrut ? {c$ds8_app_arg_5,
                                                c$ds8_app_arg_4,   nextFlush,
                                                c$ds8_app_arg_2 | c$case_alt_1[0:0],
                                                c$ds8_app_arg_1} : st;

  assign c$ds8_case_scrut = (~ st[3:3]) | r2sAc_1;

  assign r2sAc_1 = result_10[20:20];

  assign c$ds8_app_arg_1 = c$case_alt_1[1:1] ? {1'b1,st[4:4]} : {1'b0,1'bx};

  assign c$ds8_app_arg_2 = c$ds8_app_arg_3 & st[2:2];

  assign c$ds8_app_arg_selection_10 = st[1:0];

  assign c$ds8_app_arg_3 = c$ds8_app_arg_selection_10[1:1] ? 1'b0 : 1'b1;

  assign c$ds8_app_arg_4 = nextFlush ? 1'd0 : (st[4:4] + 1'd1);

  assign nextFlush = c$nextFlush_app_arg | (st[4:4] == 1'd1);

  assign c$nextFlush_app_arg = c$case_alt_1[1:1] ? 1'b1 : 1'b0;

  assign c$i_10 = st[4:4];

  assign c$vec_0 = c$case_alt_1[9:2];

  assign c$vec_1 = st[20:5];

  // vector replace begin
  genvar i_4;
  generate
  for (i_4=0;i_4<2;i_4=i_4+1) begin : vector_replace
    assign c$ds8_app_arg_5[(1-i_4)*8+:8] = ($unsigned({{(64-1) {1'b0}},c$i_10})) == i_4 ? (c$vec_0[8-1 -: 8]) : c$vec_1[(1-i_4)*8+:8];
  end
  endgenerate
  // vector replace end

  assign rstLow_0 = ~ (c$app_arg);

  assign c$case_alt_1 = rstLow_0 ? {1'b0,
                                    {1'b0,10'bxxxxxxxxxx}} : {c$ds8_case_scrut,
                                                              s2rAc_0};

  assign s2rAc_0 = result_7[10:0];

  // register begin
  always @(posedge ethRxClk ) begin : st_register
    if ( ! c$app_arg) begin
      st <= {{8'b00000000,   8'b00000000},   1'd0,   1'b0,   1'b0,   {1'b0,1'bx}};
    end else begin
      st <= c$ds8_app_arg_0;
    end
  end
  // register end

  assign result_9 = empty ? {1'b0,19'bxxxxxxxxxxxxxxxxxxx} : f1;

  assign result_10 = {~ ds1[0:0],   result_9};

  assign empty = ds1[1:1];

  assign ds1_fun_arg = (~ empty) & bwdIn;

  Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_asyncFIFOSynchronizer Clash_TinyTapeout_EthernetMac_TopEntity_topEntity_asyncFIFOSynchronizer_ds1
    ( .result (ds1)
    , .eta1 (ethRxClk)
    , .eta2 (ethTxClk)
    , .eta3 (c$app_arg)
    , .eta4 (c$bindCsr)
    , .eta7 (ds1_fun_arg)
    , .eta8 (fwdIn) );

  assign fwdIn = result_8[19:0];

  assign bwdIn = result_11[20:20];

  assign f1 = {1'b1,ds1[20:2]};

  assign result_11 = {c$case_alt_5[20:20],
                      c$case_alt_2[20:1]};

  assign s2rAc_1 = result_10[19:0];

  assign ready = c$case_alt_2[0:0];

  assign c$case_alt_selection_4 = c$ds3_app_arg_2[20:1];

  assign c$case_alt_2 = c$case_alt_selection_4[19:19] ? {c$app_arg_1,
                                                         {{1'b1,c$case_alt_3},   r2sAc_2}} : {{fwdIn_0,
                                                                                               validated},
                                                                                              {{1'b0,19'bxxxxxxxxxxxxxxxxxxx},
                                                                                               1'b1}};

  assign c$case_alt_selection_7 = cache[2:1];

  assign c$case_alt_3 = c$case_alt_selection_7[1:1] ? {cache[18:3],
                                                       cache[2:1],
                                                       cache[0:0] | (~ c$outValid_case_alt)} : cache;

  assign c$app_arg_1 = r2sAc_2 ? {fwdIn_0,
                                  1'b0} : {c$ds3_app_arg_2[20:1],
                                           c$outValid_case_alt};

  assign c$outValid_case_alt_selection_1 = cache[2:1];

  assign c$outValid_case_alt = c$outValid_case_alt_selection_1[1:1] ? (result_12 | validated) : result_12;

  assign cache = c$ds3_app_arg_2[19:1];

  assign validated = c$ds3_app_arg_2[0:0];

  assign r2sAc_2 = result_15[132:132];

  assign result_12 = c$app_arg_3 & result_13;

  // index begin
  wire  vecArray [0:2-1];
  genvar i_5;
  generate
  for (i_5=0; i_5 < 2; i_5=i_5+1) begin : mk_array
    assign vecArray[(2-1)-i_5] = xs[i_5*1+:1];
  end
  endgenerate
  assign result_13 = vecArray[($unsigned({{(64-1) {1'b0}},i1}))];
  // index end

  assign c$vec1 = {32'b01000111000100001011101110011100,
                   32'b11000111000001001101110101111011};

  assign c$vec2 = ({2 {crcState}});

  // zipWith start
  genvar i_6;
  generate
  for (i_6 = 0; i_6 < 2; i_6 = i_6 + 1) begin : zipWith
    wire [31:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[i_6*32+:32];
    wire [31:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i_6*32+:32];
    wire  c$n;
    assign c$n = zipWith_in1 == zipWith_in2;


    assign xs[i_6*1+:1] = c$n;
  end
  endgenerate
  // zipWith end

  // register begin
  always @(posedge ethTxClk ) begin : i1_register
    if ( ! c$bindCsr) begin
      i1 <= ({1 {1'bx}});
    end else begin
      i1 <= ds10[16:16];
    end
  end
  // register end

  assign c$crcState_app_arg = c$ds3_app_arg_1 ? 32'b11111111111111111111111111111111 : crcState;

  // register begin
  always @(posedge ethTxClk ) begin : crcState_register
    if ( ! c$bindCsr) begin
      crcState <= 32'b11111111111111111111111111111111;
    end else if (c$app_arg_4) begin
      crcState <= result_14;
    end
  end
  // register end

  // map begin
  genvar i_7;
  generate
  for (i_7=0; i_7 < 2; i_7 = i_7 + 1) begin : map_0
    wire [7:0] map_in_0;
    assign map_in_0 = x[i_7*8+:8];
    wire [7:0] map_out_0;
    assign map_out_0 = map_in_0;


    assign c$case_alt_4[i_7*8+:8] = map_out_0;
  end
  endgenerate
  // map end

  assign x_projection = ds10[15:0];

  assign x = x_projection;

  assign c$vec_2 = {48'b100010110010000010000000000000001101000100000100,
                    48'b010001011001000001000000000000001010001000001001,
                    48'b001000101100100000100000000000000100010000010011,
                    48'b000100010110010000010000000000001000100000100110,
                    48'b000010001011001000001000000000000001000001001101,
                    48'b000001000101100100000100000000000010000010011010,
                    48'b100010010000110000000010000000001001000100110000,
                    48'b010001001000011000000001000000000010001001100001,
                    48'b101000100100001100000000100000000100010111000010,
                    48'b010110100000000100000000010000000101101010000000,
                    48'b001001100010000000000000001000000110010000000100,
                    48'b000100110001000000000000000100001100100000001000,
                    48'b100010011000100000000000000010001001000100010001,
                    48'b110001001100010000000000000001000010001100100011,
                    48'b011000100110001000000000000000100100011001000110,
                    48'b001100010011000100000000000000011000110010001100,
                    48'b100100111011100000000000000000001100100100011101,
                    48'b110010011101110000000000000000001001001100111011,
                    48'b011001001110111000000000000000000010011001110111,
                    48'b101100100111011100000000000000000100110111101110,
                    48'b110100100001101100000000000000000100101111011000,
                    48'b011000100010110100000000000000000100011010110100,
                    48'b001110100011011000000000000000000101110001101100,
                    48'b000111010001101100000000000000001011100011011000,
                    48'b100001011010110100000000000000001010000110110101,
                    48'b010010011111011000000000000000001001001001101111,
                    48'b001001001111101100000000000000000010010011011111,
                    48'b100110010101110100000000000000001001100110111010,
                    48'b110001111000111000000000000000001110001101110001,
                    48'b011000111100011100000000000000001100011011100011,
                    48'b001110101100001100000000000000000101110011000011,
                    48'b000101100100000100000000000000000110100010000010};

  // map begin
  genvar i_8;
  generate
  for (i_8=0; i_8 < 32; i_8 = i_8 + 1) begin : map_1
    wire [47:0] map_in_1;
    assign map_in_1 = c$vec_2[i_8*48+:48];
    wire  map_out_1;
    assign map_out_1 = ^ (((({c$crcState_app_arg,((c$case_alt_4))}) & map_in_1)));


    assign c$app_arg_2[i_8*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign result_14 = ((c$app_arg_2));

  assign ds10 = c$ds3_app_arg[17:17] ? a1_1 : ({17 {1'bx}});

  assign a1_1 = c$ds3_app_arg[16:0];

  // register begin
  always @(posedge ethTxClk ) begin : c$app_arg_3_register
    if ( ! c$bindCsr) begin
      c$app_arg_3 <= 1'b0;
    end else begin
      c$app_arg_3 <= c$app_arg_4;
    end
  end
  // register end

  assign c$app_arg_4 = c$ds3_app_arg[17:17] ? 1'b1 : 1'b0;

  assign c$ds3_app_arg = transferOccured ? {1'b1,{c$ds3_app_arg_0,
                                                  fwdInX[18:3]}} : {1'b0,17'bxxxxxxxxxxxxxxxxx};

  assign c$ds3_app_arg_selection_2 = fwdInX[2:1];

  assign c$ds3_app_arg_0 = c$ds3_app_arg_selection_2[1:1] ? v : 1'd1;

  assign v = fwdInX[1:1];

  // register begin
  always @(posedge ethTxClk ) begin : c$ds3_app_arg_1_register
    if ( ! c$bindCsr) begin
      c$ds3_app_arg_1 <= 1'b1;
    end else if (transferOccured) begin
      c$ds3_app_arg_1 <= c$ds3_case_alt;
    end
  end
  // register end

  assign c$ds3_case_alt_selection_1 = fwdInX[2:1];

  assign c$ds3_case_alt = c$ds3_case_alt_selection_1[1:1] ? 1'b1 : 1'b0;

  assign fwdInX = fwdIn_0[19:19] ? a1_2 : ({19 {1'bx}});

  assign a1_2 = fwdIn_0[18:0];

  assign transferOccured = ready & c$transferOccured_app_arg;

  assign c$transferOccured_app_arg = fwdIn_0[19:19] ? 1'b1 : 1'b0;

  assign fwdIn_0 = c$case_alt_5[19:0];

  assign rstLow_1 = ~ (c$bindCsr);

  assign c$case_alt_5 = rstLow_1 ? {1'b0,
                                    {1'b0,19'bxxxxxxxxxxxxxxxxxxx}} : {ready,
                                                                       s2rAc_1};

  // register begin
  always @(posedge ethTxClk ) begin : c$ds3_app_arg_2_register
    if ( ! c$bindCsr) begin
      c$ds3_app_arg_2 <= {{1'b0,19'bxxxxxxxxxxxxxxxxxxx},   1'b0};
    end else begin
      c$ds3_app_arg_2 <= c$case_alt_2[41:21];
    end
  end
  // register end

  assign result_15 = {c$case_alt_7[20:20],
                      result_16[131:0]};

  // map begin
  genvar i_9;
  generate
  for (i_9=0; i_9 < 14; i_9 = i_9 + 1) begin : map_2
    wire [7:0] map_in_2;
    assign map_in_2 = c$mapOut_app_arg_0[i_9*8+:8];
    wire [7:0] map_out_2;
    assign map_out_2 = map_in_2;


    assign c$mapOut_0[i_9*8+:8] = map_out_2;
  end
  endgenerate
  // map end

  assign c$mapOut_app_arg_sel_alt_4 = eta6_0[115:4];

  assign c$mapOut_app_arg_sel_alt_6 = eta6_0[115:4];

  always @(*) begin
    case(eta6_0[118:117])
      2'b01 : c$mapOut_app_arg_0 = c$mapOut_app_arg_sel_alt_4;
      default : c$mapOut_app_arg_0 = c$mapOut_app_arg_sel_alt_6;
    endcase
  end

  // register begin
  always @(posedge ethTxClk ) begin : eta6_0_register
    if ( ! c$bindCsr) begin
      eta6_0 <= {2'b00,1'b0,{{8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},   {8 {1'bx}},
               {8 {1'bx}},   {8 {1'bx}}},3'd6,1'bx};
    end else begin
      eta6_0 <= result_16[251:133];
    end
  end
  // register end

  always @(*) begin
    case(eta6_0[118:117])
      2'b00 : result_16 = c$ds2_case_alt_12;
      2'b01 : result_16 = c$ds2_case_alt_7;
      default : result_16 = {c$ds2_app_arg_8,
                             {r2sAc_3,   {1'b1,{{2 {8'b00000000}},
                                                {1'b1,c$ds2_app_arg_7 - 1'd0},   result_17,
                                                eta6_0[116:116] | c$ds2_app_arg_6}}}};
    endcase
  end

  assign c$ds2_app_arg_selection_12 = c$case_alt_7[19:0];

  assign c$ds2_app_arg_6 = c$ds2_app_arg_selection_12[19:19] ? c$case_alt_7[0:0] : ({1 {1'bx}});

  assign c$ds2_app_arg_selection_15 = c$case_alt_7[19:0];

  assign c$ds2_app_arg_7 = c$ds2_app_arg_selection_15[19:19] ? c$ds2_case_alt_6 : ({1 {1'bx}});

  assign c$ds2_case_alt_selection_20 = c$case_alt_7[2:1];

  assign c$ds2_case_alt_6 = c$ds2_case_alt_selection_20[1:1] ? a1_3 : ({1 {1'bx}});

  assign c$ds2_app_arg_8 = r2sAc_3 ? {2'b00,1'b0,eta6_0[115:4],3'd6,1'bx} : eta6_0;

  assign c$ds2_case_alt_selection_23 = c$case_alt_7[19:0];

  assign c$ds2_case_alt_7 = c$ds2_case_alt_selection_23[19:19] ? {c$ds2_app_arg_11,
                                                                  {c$ds2_app_arg_10,   {1'b1,{ds11_0,
                                                                                              c$ds2_app_arg_9,
                                                                                              result_17,
                                                                                              nextAborted_1}}}} : {eta6_0,
                                                                                                                   {r2sAc_3,
                                                                                                                    {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds2_app_arg_9 = newLast_0[2:2] ? c$ds2_case_alt_8 : {1'b0,1'bx};

  assign c$ds2_case_alt_selection_26 = newLast_0[1:0];

  assign c$ds2_case_alt_8 = c$ds2_case_alt_selection_26[1:1] ? {1'b0,1'bx} : {1'b1,x1_0};

  assign x1_0 = newLast_0[0:0];

  assign c$ds1_case_alt_0 = back;

  assign result_17 = {(ds4[111:64]),
                      (c$ds1_case_alt_0[63:16]),
                      c$ds1_case_alt_0[15:0]};

  assign ds4 = ((c$mapOut_0));

  assign back = ds4[63:0];

  assign c$ds2_app_arg_10 = newLast_0[2:2] ? c$ds2_case_alt_9 : r2sAc_3;

  assign c$ds2_case_alt_selection_29 = newLast_0[1:0];

  assign c$ds2_case_alt_9 = c$ds2_case_alt_selection_29[1:1] ? 1'b0 : r2sAc_3;

  assign c$ds2_app_arg_11 = r2sAc_3 ? c$ds2_case_alt_10 : eta6_0;

  assign c$ds2_case_alt_10 = newLast_0[2:2] ? c$ds2_case_alt_11 : {2'b01,nextAborted_1,eta6_0[115:4],eta6_0[3:1],1'bx};

  assign c$ds2_case_alt_selection_33 = newLast_0[1:0];

  assign c$ds2_case_alt_11 = c$ds2_case_alt_selection_33[1:1] ? {2'b10,nextAborted_1,eta6_0[115:4],eta6_0[3:1],idx_0} : {2'b00,1'b0,eta6_0[115:4],3'd6,1'bx};

  assign idx_0 = newLast_0[0:0];

  assign newLast_selection_7 = c$case_alt_7[2:1];

  assign newLast_0 = newLast_selection_7[1:1] ? {1'b1,{1'b0,a1_3 + 1'd0}} : {1'b0,2'bxx};

  assign a1_3 = c$case_alt_7[1:1];

  assign nextAborted_1 = eta6_0[116:116] | c$case_alt_7[0:0];

  assign ds11_0 = c$case_alt_7[18:3];

  assign c$ds2_case_alt_selection_36 = c$case_alt_7[19:0];

  assign c$ds2_case_alt_12 = c$ds2_case_alt_selection_36[19:19] ? {result_18,
                                                                   {c$ds2_app_arg_12,
                                                                    {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}} : {eta6_0,
                                                                                                                                                                                                                         {r2sAc_3,
                                                                                                                                                                                                                          {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}};

  assign r2sAc_3 = result_20[132:132];

  always @(*) begin
    case(result_18[118:117])
      2'b10 : c$ds2_app_arg_12 = 1'b0;
      default : c$ds2_app_arg_12 = 1'b1;
    endcase
  end

  assign result_18 = ds13_0 ? result_19 : c$nextSt_case_alt_0;

  assign c$nextSt_case_alt_selection_7 = c$case_alt_7[2:1];

  assign c$nextSt_case_alt_0 = c$nextSt_case_alt_selection_7[1:1] ? result_19 : {2'b00,nextAborted_2,nextParseBuf_0,nextCounter_0,1'bx};

  assign c$case_alt_6 = ds13_0 ? {2'b01,nextAborted_2,nextParseBuf_0,nextCounter_0,1'bx} : ({119 {1'bx}});

  assign result_selection_13 = c$case_alt_7[2:1];

  assign result_19 = result_selection_13[1:1] ? {2'b00,1'b0,nextParseBuf_0,3'd6,1'bx} : c$case_alt_6;

  assign nextAborted_2 = eta6_0[116:116] | c$case_alt_7[0:0];

  assign nextParseBuf_projection_6 = ({eta6_0[115:4],c$case_alt_7[18:3]});

  assign nextParseBuf_0 = nextParseBuf_projection_6[111:0];

  assign fwdBuf_projection_4 = c$case_alt_7[18:3];

  assign nextCounter_0 = eta6_0[3:1] - 3'd1;

  assign rstLow_2 = ~ (c$bindCsr);

  assign bwd_0 = result_16[132:132];

  assign c$case_alt_7 = rstLow_2 ? {1'b0,
                                    {1'b0,19'bxxxxxxxxxxxxxxxxxxx}} : {bwd_0,
                                                                       s2rAc_2};

  assign s2rAc_2 = result_11[19:0];

  assign ds13_0 = eta6_0[3:1] == 3'd0;

  assign result_20 = wild1_0[131:131] ? c$ds17_case_alt : {result_32[132:132],
                                                           {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign c$ds17_case_alt = result_21 ? {result_32[132:132],
                                        wild1_0} : {1'b1,
                                                    {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign result_21 = c$case_alt_9 | c$case_alt_8;

  wire [5:0] vec;
  wire  acc_3_0;
  wire  acc_1;
  wire  acc_2;
  wire  acc_3;
  wire  acc_4;
  wire  acc_5;
  wire  acc_6;
  wire  acc_1_0;
  wire  acc_1_1;
  wire  acc_2_0;
  wire  acc_1_2;
  assign c$case_alt_8 = acc_3_0;

  assign vec = c$app_arg_5;

  assign acc_1 = vec[5:5];

  assign acc_2 = vec[4:4];

  assign acc_3 = vec[3:3];

  assign acc_4 = vec[2:2];

  assign acc_5 = vec[1:1];

  assign acc_6 = vec[0:0];

  assign acc_1_0 = acc_1 & acc_2;



  assign acc_1_1 = acc_3 & acc_4;



  assign acc_1_2 = acc_5 & acc_6;



  assign acc_2_0 = acc_1_0 & acc_1_1;



  assign acc_3_0 = acc_2_0 & acc_1_2;





  assign c$vec1_0 = inPkt_0[112:65];

  assign c$vec2_0 = ({6 {8'b11111111}});

  // zipWith start
  genvar i_10;
  generate
  for (i_10 = 0; i_10 < 6; i_10 = i_10 + 1) begin : zipWith_0
    wire [7:0] zipWith_in1_0;
    assign zipWith_in1_0 = c$vec1_0[i_10*8+:8];
    wire [7:0] zipWith_in2_0;
    assign zipWith_in2_0 = c$vec2_0[i_10*8+:8];
    wire  c$n_0;
    assign c$n_0 = zipWith_in1_0 == zipWith_in2_0;


    assign c$app_arg_5[i_10*1+:1] = c$n_0;
  end
  endgenerate
  // zipWith end

  wire [5:0] vec_0;
  wire  acc_3_0_4;
  wire  acc_0_4;
  wire  acc_0_5;
  wire  acc_0_6;
  wire  acc_0_7;
  wire  acc_0_8;
  wire  acc_0_9;
  wire  acc_1_0_0;
  wire  acc_1_1_1;
  wire  acc_2_0_3;
  wire  acc_1_2_2;
  assign c$case_alt_9 = acc_3_0_4;

  assign vec_0 = c$app_arg_6;

  assign acc_0_4 = vec_0[5:5];

  assign acc_0_5 = vec_0[4:4];

  assign acc_0_6 = vec_0[3:3];

  assign acc_0_7 = vec_0[2:2];

  assign acc_0_8 = vec_0[1:1];

  assign acc_0_9 = vec_0[0:0];

  assign acc_1_0_0 = acc_0_4 & acc_0_5;



  assign acc_1_1_1 = acc_0_6 & acc_0_7;



  assign acc_1_2_2 = acc_0_8 & acc_0_9;



  assign acc_2_0_3 = acc_1_0_0 & acc_1_1_1;



  assign acc_3_0_4 = acc_2_0_3 & acc_1_2_2;





  assign c$vec1_1 = inPkt_0[112:65];

  assign c$vec2_1 = {8'b01011110,   8'b10100100,
                     8'b01001110,   8'b11110100,   8'b00100001,
                     8'b00000110};

  // zipWith start
  genvar i_11;
  generate
  for (i_11 = 0; i_11 < 6; i_11 = i_11 + 1) begin : zipWith_1
    wire [7:0] zipWith_in1_1;
    assign zipWith_in1_1 = c$vec1_1[i_11*8+:8];
    wire [7:0] zipWith_in2_1;
    assign zipWith_in2_1 = c$vec2_1[i_11*8+:8];
    wire  c$n_1;
    assign c$n_1 = zipWith_in1_1 == zipWith_in2_1;


    assign c$app_arg_6[i_11*1+:1] = c$n_1;
  end
  endgenerate
  // zipWith end

  assign inPkt_0 = wild1_0[130:0];

  assign wild1_0 = result_15[131:0];

  // register begin
  always @(posedge ethTxClk ) begin : c$ds_app_arg_register
    if ( ! c$bindCsr) begin
      c$ds_app_arg <= {4'd0,   {{{8 {1'bx}},   {8 {1'bx}}},   {{8 {1'bx}},   {8 {1'bx}}}},   2'd0,
   1'b0};
    end else begin
      c$ds_app_arg <= c$case_alt_11[170:132];
    end
  end
  // register end

  assign c$case_alt_10 = {bwdIn_0,
                          c$case_alt_11[131:0]};

  assign c$vec_3 = result_27[133:132];

  assign c$vec_4 = (c$vec_3[1-1 : 0]);

  assign bwdIn_0 = c$vec_4[1-1 -: 1];

  assign c$vec_5 = result_25[263:0];

  assign c$vec_6 = (c$vec_5[132-1 : 0]);

  assign c$case_alt_selection_res = c$vec_6[132-1 -: 132];

  assign c$case_alt_11 = c$case_alt_selection_res[131:131] ? {c$app_arg_9,
                                                              {1'b1,{c$app_arg_7,   ipv[114:113],
                                                                     ipv[112:1],   result_24}}} : {c$ds_app_arg,
                                                                                                   {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign c$app_arg_selection_6 = c$ds_app_arg[38:35];

  always @(*) begin
    case(c$app_arg_selection_6)
      4'b0100 : c$app_arg_7 = c$mapOut_app_arg_1;
      4'b0110 : c$app_arg_7 = {8'b00000000,
                               8'b00000000};
      4'b0111 : c$app_arg_7 = ((((~ result_22))));
      default : c$app_arg_7 = dataOut0;
    endcase
  end

  assign a = ~ (((c$app_arg_8)));

  assign summed = a + 16'd63487;

  assign c$bv = ((summed));

  assign c$bv_0 = (((( c$bv[17-1] ))));

  assign result_22 = (summed[0+:16]) + ({{(16-1) {1'b0}},(((( c$bv[17-1] ))))});

  // map begin
  genvar i_12;
  generate
  for (i_12=0; i_12 < 2; i_12 = i_12 + 1) begin : map_3
    wire [7:0] map_in_3;
    assign map_in_3 = dataOut0[i_12*8+:8];
    wire [7:0] map_out_3;
    assign map_out_3 = map_in_3;


    assign c$app_arg_8[i_12*8+:8] = map_out_3;
  end
  endgenerate
  // map end

  assign dataOut0_selection_1 = c$ds_app_arg[38:35];

  always @(*) begin
    case(dataOut0_selection_1)
      4'b0101 : dataOut0 = c$dataOut0_case_alt;
      default : dataOut0 = c$dataOut0_case_alt_0;
    endcase
  end

  assign c$vec_7 = result_27[133:132];

  assign c$vec_8 = (c$vec_7[1-1 : 0]);

  assign c$app_arg_9 = (~ (c$vec_8[1-1 -: 1])) ? c$ds_app_arg : {c$case_alt_17,
                                                                 dShift2[48-1 : 16],   c$case_alt_12,
                                                                 result_24};

  assign c$case_alt_selection_14 = ipv[114:113];

  assign c$case_alt_12 = c$case_alt_selection_14[1:1] ? c$case_alt_15 : c$case_alt_13;

  assign c$case_alt_selection_17 = c$ds_app_arg[38:35];

  always @(*) begin
    case(c$case_alt_selection_17)
      4'b1000 : c$case_alt_13 = c$case_alt_16;
      default : c$case_alt_13 = c$case_alt_14;
    endcase
  end

  assign c$case_alt_14 = stateCntZero ? c$case_alt_15 : c$case_alt_16;

  always @(*) begin
    case(c$nextFsm_case_alt)
      4'b0001 : c$case_alt_15 = 2'd2;
      4'b0100 : c$case_alt_15 = 2'd1;
      4'b0101 : c$case_alt_15 = 2'd1;
      4'b1000 : c$case_alt_15 = {2 {1'bx}};
      default : c$case_alt_15 = 2'd0;
    endcase
  end

  assign c$case_alt_16 = c$ds_app_arg[2:1] - 2'd1;

  assign c$case_alt_selection_22 = ipv[114:113];

  assign c$case_alt_17 = c$case_alt_selection_22[1:1] ? c$nextFsm_case_alt : c$case_alt_18;

  assign c$case_alt_selection_25 = c$ds_app_arg[38:35];

  always @(*) begin
    case(c$case_alt_selection_25)
      4'b1000 : c$case_alt_18 = 4'd8;
      default : c$case_alt_18 = c$case_alt_19;
    endcase
  end

  assign c$case_alt_19 = stateCntZero ? c$nextFsm_case_alt : c$ds_app_arg[38:35];

  assign c$nextFsm_case_alt_selection_1 = ipv[114:113];

  assign c$nextFsm_case_alt = c$nextFsm_case_alt_selection_1[1:1] ? 4'd0 : c$nextFsm_case_alt_0;

  assign c$nextFsm_case_alt_selection_4 = c$ds_app_arg[38:35];

  always @(*) begin
    case(c$nextFsm_case_alt_selection_4)
      4'b1000 : c$nextFsm_case_alt_0 = {4 {1'bx}};
      default : c$nextFsm_case_alt_0 = result_23;
    endcase
  end

  assign c$tte_rhs = \a#  + 64'sd1;

  assign result_23 = $unsigned(c$tte_rhs);

  assign c$dtt_rhs_1 = c$ds_app_arg[38:35];

  assign \a#  = $unsigned(c$dtt_rhs_1);

  assign c$dataOut0_case_alt = dShift2[15:0];

  assign c$dataOut0_case_alt_0 = dShift2[47:32];

  assign dShift2 = {dShift1,
                    c$ds_app_arg[34:3]};

  assign result_selection_17 = c$ds_app_arg[38:35];

  always @(*) begin
    case(result_selection_17)
      4'b0000 : result_24 = errNow;
      default : result_24 = c$ds_app_arg[0:0] | errNow;
    endcase
  end

  assign errNow = ipv[0:0] | c$foldOut;

  wire [1:0] vec_1;
  wire  acc_1_0_5;
  wire  acc_0_11;
  wire  acc_0_12;
  assign c$foldOut = acc_1_0_5;

  assign vec_1 = (c$zipWithOut);

  assign acc_0_11 = vec_1[1:1];

  assign acc_0_12 = vec_1[0:0];

  assign acc_1_0_5 = acc_0_11 | acc_0_12;





  // zipWith start
  genvar i_13;
  generate
  for (i_13 = 0; i_13 < 2; i_13 = i_13 + 1) begin : zipWith_2
    wire [8:0] zipWith_in1_2;
    assign zipWith_in1_2 = c$zipWithOut_app_arg[i_13*9+:9];
    wire [7:0] zipWith_in2_2;
    assign zipWith_in2_2 = dShift1[i_13*8+:8];
    wire  c$n_2;
    wire [7:0] check;
    wire  result_56;
    assign c$n_2 = result_56;

    assign check = zipWith_in1_2[7:0];

    assign result_56 = zipWith_in1_2[8:8] ? (check != zipWith_in2_2) : 1'b0;


    assign c$zipWithOut[i_13*1+:1] = c$n_2;
  end
  endgenerate
  // zipWith end

  assign dShift1 = ipv[130:115];

  assign c$vec_9 = result_25[263:0];

  assign c$vec_10 = (c$vec_9[132-1 : 0]);

  assign ipv_projection = c$vec_10[132-1 -: 132];

  assign ipv = ipv_projection[130:0];

  assign c$zipWithOut_app_arg_selection_1 = c$ds_app_arg[38:35];

  always @(*) begin
    case(c$zipWithOut_app_arg_selection_1)
      4'b0000 : c$zipWithOut_app_arg = {{1'b1,8'b01000101},
                                        {1'b0,8'bxxxxxxxx}};
      4'b0010 : c$zipWithOut_app_arg = {{1'b0,8'bxxxxxxxx},
                                        {1'b1,8'b00000001}};
      4'b0101 : c$zipWithOut_app_arg = c$mapOut_1;
      4'b0110 : c$zipWithOut_app_arg = {{1'b1,8'b00001000},
                                        {1'b1,8'b00000000}};
      default : c$zipWithOut_app_arg = {2 {{1'b0,8'bxxxxxxxx}}};
    endcase
  end

  // map begin
  genvar i_14;
  generate
  for (i_14=0; i_14 < 2; i_14 = i_14 + 1) begin : map_4
    wire [7:0] map_in_4;
    assign map_in_4 = c$mapOut_app_arg_1[i_14*8+:8];
    wire [8:0] map_out_4;
    assign map_out_4 = {1'b1,map_in_4};


    assign c$mapOut_1[i_14*9+:9] = map_out_4;
  end
  endgenerate
  // map end

  assign c$vec_11 = {8'b00001010,   8'b00000000,
                     8'b00000000,   8'b00000010};

  // map begin
  genvar i_15;
  generate
  for (i_15=0; i_15 < 4; i_15 = i_15 + 1) begin : map_5
    wire [7:0] map_in_5;
    assign map_in_5 = c$vec_11[i_15*8+:8];
    wire [7:0] map_out_5;
    assign map_out_5 = map_in_5;


    assign c$mapOut_app_arg_sel_alt_t_res_res[i_15*8+:8] = map_out_5;
  end
  endgenerate
  // map end

  assign c$vec_12 = (((c$mapOut_app_arg_sel_alt_t_res_res)));

  // map begin
  genvar i_16;
  generate
  for (i_16=0; i_16 < 2; i_16 = i_16 + 1) begin : map_6
    wire [15:0] map_in_6;
    assign map_in_6 = c$vec_12[i_16*16+:16];
    wire [15:0] map_out_6;
    assign map_out_6 = (map_in_6);


    assign c$mapOut_app_arg_sel_alt_t_res[i_16*16+:16] = map_out_6;
  end
  endgenerate
  // map end

  assign c$vec_13 = {8'b00001010,   8'b00000000,
                     8'b00000000,   8'b00000010};

  // map begin
  genvar i_17;
  generate
  for (i_17=0; i_17 < 4; i_17 = i_17 + 1) begin : map_7
    wire [7:0] map_in_7;
    assign map_in_7 = c$vec_13[i_17*8+:8];
    wire [7:0] map_out_7;
    assign map_out_7 = map_in_7;


    assign c$mapOut_app_arg_sel_alt_f_res_res[i_17*8+:8] = map_out_7;
  end
  endgenerate
  // map end

  assign c$vec_14 = (((c$mapOut_app_arg_sel_alt_f_res_res)));

  // map begin
  genvar i_18;
  generate
  for (i_18=0; i_18 < 2; i_18 = i_18 + 1) begin : map_8
    wire [15:0] map_in_8;
    assign map_in_8 = c$vec_14[i_18*16+:16];
    wire [15:0] map_out_8;
    assign map_out_8 = (map_in_8);


    assign c$mapOut_app_arg_sel_alt_f_res[i_18*16+:16] = map_out_8;
  end
  endgenerate
  // map end

  assign c$mapOut_app_arg_1 = stateCntZero ? (c$mapOut_app_arg_sel_alt_t_res[16-1:0]) : (c$mapOut_app_arg_sel_alt_f_res[32-1 -: 16]);

  assign stateCntZero = c$ds_app_arg[2:1] == 2'd0;

  assign result_25 = {ds[264:264],   ds[263:0]};

  assign ds = eth_Fwd[131:131] ? result_26 : {1'b0,
                                              {2 {{1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}}};

  assign result_26 = c$ds_case_scrut[1:1] ? {c$ds_app_arg_1,
                                             c$ds_app_arg_0} : {1'b1,
                                                                {2 {{1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}}};

  assign c$vec_15 = {{1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
                     {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  // vector replace begin
  genvar i_19;
  generate
  for (i_19=0;i_19<2;i_19=i_19+1) begin : vector_replace_0
    assign c$ds_app_arg_0[(1-i_19)*132+:132] = c$ds_app_arg_2 == i_19 ? eth_Fwd : c$vec_15[(1-i_19)*132+:132];
  end
  endgenerate
  // vector replace end

  assign c$vecFlat = {result_30[132:132],
                      c$case_alt_10[132:132]};

  // index begin
  wire  vecArray_0 [0:2-1];
  genvar i_20;
  generate
  for (i_20=0; i_20 < 2; i_20=i_20+1) begin : mk_array_0
    assign vecArray_0[(2-1)-i_20] = c$vecFlat[i_20*1+:1];
  end
  endgenerate
  assign c$ds_app_arg_1 = vecArray_0[c$ds_app_arg_2];
  // index end

  assign c$ds_app_arg_2 = $unsigned({{(64-1) {1'b0}},i});

  assign i = c$ds_case_scrut[0:0];

  assign c$ds_case_scrut = ws[6-1 -: 2];

  assign ws = {c$ws_app_arg,{1'b0,1'bx}};

  // imap begin
  genvar i_22;
  generate
  for (i_22=0; i_22 < 2; i_22 = i_22 + 1) begin : imap
    wire [1-1:0] map_index;
    wire [2:0] map_in_9;
    assign map_in_9 = c$ws_app_arg_0[i_22*3+:3];
    wire [1:0] map_out_9;

    assign map_index = 1'd1 - i_22[0+:1];
    wire  x_6;
    wire [1:0] c$case_alt_30;
    assign map_out_9 = c$case_alt_30;

    assign x_6 = map_in_9[2:2];

    assign c$case_alt_30 = x_6 ? {1'b1,map_index} : map_in_9[1:0];


    assign c$ws_app_arg[i_22*2+:2] = map_out_9;
  end
  endgenerate
  // imap end

  assign c$vec1_2 = {16'b0010000000000010 == x_0[16:1],
                     16'b0000100000000000 == x_0[16:1]};

  assign c$vec2_2 = (ws[4-1 : 0]);

  // zipWith start
  genvar i_23;
  generate
  for (i_23 = 0; i_23 < 2; i_23 = i_23 + 1) begin : zipWith_3
    wire  zipWith_in1_3;
    assign zipWith_in1_3 = c$vec1_2[i_23*1+:1];
    wire [1:0] zipWith_in2_3;
    assign zipWith_in2_3 = c$vec2_2[i_23*2+:2];
    wire [2:0] c$n_3;
    assign c$n_3 = {zipWith_in1_3,   zipWith_in2_3};


    assign c$ws_app_arg_0[i_23*3+:3] = c$n_3;
  end
  endgenerate
  // zipWith end

  assign x_0 = eth_Fwd[130:0];

  assign result_27 = {c$ds1_app_arg,   fwd};

  assign c$vec_16 = {1'b0,   1'b0};

  // vector replace begin
  genvar i_24;
  generate
  for (i_24=0;i_24<2;i_24=i_24+1) begin : vector_replace_1
    assign c$ds1_app_arg[(1-i_24)*1+:1] = c$fwd_app_arg == i_24 ? \final:stmt_Bwd  : c$vec_16[(1-i_24)*1+:1];
  end
  endgenerate
  // vector replace end

  assign c$ds1_app_arg_0 = fwd[131:131] ? c$ds1_case_alt_1 : first;

  assign c$ds1_case_alt_selection_5 = fwd[114:113];

  assign c$ds1_case_alt_1 = c$ds1_case_alt_selection_5[1:1] ? \final:stmt_Bwd  : 1'b0;

  assign result_28 = fwd[131:131] ? c$ds1_case_alt_3 : c$ds1_case_alt_2;

  assign c$ds1_case_alt_2 = first ? result_29 : i_0;

  assign first = ds2[0:0];

  assign c$ds1_case_alt_selection_10 = fwd[114:113];

  assign c$ds1_case_alt_3 = c$ds1_case_alt_selection_10[1:1] ? c$ds1_case_alt_4 : i_0;

  assign c$vecFlat_0 = {result_30[131:0],
                        c$case_alt_10[131:0]};

  // index begin
  wire [131:0] vecArray_1 [0:2-1];
  genvar i_25;
  generate
  for (i_25=0; i_25 < 2; i_25=i_25+1) begin : mk_array_1
    assign vecArray_1[(2-1)-i_25] = c$vecFlat_0[i_25*132+:132];
  end
  endgenerate
  assign fwd = vecArray_1[c$fwd_app_arg];
  // index end

  assign c$fwd_app_arg = $unsigned({{(64-1) {1'b0}},i_0});

  assign c$ds1_case_alt_4 = \final:stmt_Bwd  ? result_29 : i_0;

  assign z = i_0 + 1'd1;

  assign c$bv_1 = (z - 2'd2);

  assign result_29 = (z >= 2'd2) ? (c$bv_1[0+:1]) : (z[0+:1]);

  assign i_0 = ds2[1:1];

  // register begin
  always @(posedge ethTxClk ) begin : ds2_register
    if ( ! c$bindCsr) begin
      ds2 <= {1'd1,   1'b1};
    end else begin
      ds2 <= {result_28,   c$ds1_app_arg_0};
    end
  end
  // register end

  // register begin
  always @(posedge ethTxClk ) begin : c$ds1_app_arg_1_register
    if ( ! c$bindCsr) begin
      c$ds1_app_arg_1 <= 7'd0;
    end else begin
      c$ds1_app_arg_1 <= c$case_alt_20[146:140];
    end
  end
  // register end

  assign c$i_104 = c$case_alt_20[139:133];

  // romBlob begin
  reg [15:0] ROM [0:121-1];

  reg [1935:0] rom_init;
  integer i_26;
  initial begin
    rom_init = {16'b0011110100111101,   16'b0011111000100000,   16'b0101010001101001,
   16'b0110111001111001,   16'b0101010001100001,   16'b0111000001100101,
   16'b0110111101110101,   16'b0111010000100000,   16'b0100001101101100,
   16'b0110000101110011,   16'b0110100000100000,   16'b0110001001100001,
   16'b0111001101100101,   16'b0110010000100000,   16'b0100010101110100,
   16'b0110100001100101,   16'b0111001001101110,   16'b0110010101110100,
   16'b0010000001001101,   16'b0100000101000011,   16'b0010000000111100,
   16'b0011110100111101,   16'b0000101000001010,   16'b0100010001100101,
   16'b0111001101101001,   16'b0110011101101110,   16'b0110010101100100,
   16'b0010000001100010,   16'b0111100100111010,   16'b0000101000001001,
   16'b0100101001100001,   16'b0111001101110000,   16'b0110010101110010,
   16'b0010000001001100,   16'b0110000101110101,   16'b0110110101100101,
   16'b0110111000001010,   16'b0000100101001101,   16'b0110000101110010,
   16'b0111010000100000,   16'b0100101101101111,   16'b0111001101110100,
   16'b0110010101110010,   16'b0000101000001001,   16'b0100010001100001,
   16'b0110000101101110,   16'b0010000001010111,   16'b0110010101100101,
   16'b0111001101110011,   16'b0110100101100101,   16'b0111001100001010,
   16'b0000100101000011,   16'b0110000101110100,   16'b0110111100100000,
   16'b0111011001100001,   16'b0110111000100000,   16'b0100111101101010,
   16'b0110010101101110,   16'b0000101000001001,   16'b0100101001100001,
   16'b0111001101101101,   16'b0110100101101010,   16'b0110111000100000,
   16'b0100001001101111,   16'b0110111101101011,   16'b0110010101101100,
   16'b0110110101100001,   16'b0110111001101110,   16'b0000101000001001,
   16'b0101010001101001,   16'b0110110100100000,   16'b0101011101100001,
   16'b0110110001101100,   16'b0110010101110100,   16'b0000101000001001,
   16'b0100001001110010,   16'b0111100101100001,   16'b0110111000100000,
   16'b0101001001101001,   16'b0110111001100100,   16'b0110010101110010,
   16'b0111001100001010,   16'b0000100101001101,   16'b0110000101110100,
   16'b0111010001101000,   16'b0110100101101010,   16'b0111001100100000,
   16'b0100110101110101,   16'b0110100101110011,   16'b0000101000001001,
   16'b0101001001101111,   16'b0111011101100001,   16'b0110111000100000,
   16'b0100011101101111,   16'b0110010101101101,   16'b0110000101101110,
   16'b0111001100001010,   16'b0000100101010000,   16'b0110010101110100,
   16'b0110010101110010,   16'b0010000001001100,   16'b0110010101100010,
   16'b0110001001101001,   16'b0110111001100111,   16'b0000101000001010,
   16'b0010000000111101,   16'b0011110100111110,   16'b0010000001010011,
   16'b0111000001101111,   16'b0110111001110011,   16'b0110111101110010,
   16'b0110010101100100,   16'b0010000001100010,   16'b0111100100100000,
   16'b0101000101100010,   16'b0110000101111001,   16'b0100110001101111,
   16'b0110011101101001,   16'b0110001100100000,   16'b0011110000111101,
   16'b0011110100000000};
    for (i_26=0; i_26 < 121; i_26 = i_26 + 1) begin
      ROM[121-1-i_26] = rom_init[i_26*16+:16];
    end
  end

  always @(posedge ethTxClk) begin : topEntity_rom
    c$ds1_app_arg_2 <= ROM[($unsigned({{(64-7) {1'b0}},c$i_104}))];
  end
  // romBlob end

  assign result_30 = {c$case_alt_20[132:132],
                      c$case_alt_20[131:0]};

  assign c$case_alt_20 = fwdIn_2[131:131] ? {nextCnt,
                                             {nextCnt,
                                              c$case_alt_22 | (lastWord & bwdIn_1),
                                              c$case_alt_21}} : {c$ds1_app_arg_1,
                                                                 {c$ds1_app_arg_1,   bwdIn_1,
                                                                  {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}}};

  assign nextCnt = (c$nextCnt_case_alt & bwdIn_1) ? result_31 : c$ds1_app_arg_1;

  assign c$case_alt_selection_31 = fwdIn_1[114:113];

  assign c$case_alt_21 = c$case_alt_selection_31[1:1] ? {1'b1,{(c$ds1_app_arg_2),
                                                               c$app_arg_10,   fwdIn_1[112:1],
                                                               fwdIn_1[0:0]}} : {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$app_arg_10 = lastWord ? {1'b1,1'd1} : {1'b0,1'bx};

  assign lastWord = c$ds1_app_arg_1 == 7'd120;

  assign c$case_alt_selection_34 = fwdIn_1[114:113];

  assign c$case_alt_22 = c$case_alt_selection_34[1:1] ? 1'b0 : 1'b1;

  assign z_0 = c$ds1_app_arg_1 + 7'd1;

  assign c$bv_2 = (z_0 - 8'd121);

  assign result_31 = (z_0 >= 8'd121) ? (c$bv_2[0+:7]) : (z_0[0+:7]);

  assign c$nextCnt_case_alt_selection_1 = fwdIn_1[114:113];

  assign c$nextCnt_case_alt = c$nextCnt_case_alt_selection_1[1:1] ? 1'b1 : 1'b0;

  assign fwdIn_1 = fwdIn_2[130:0];

  assign c$vec_17 = result_25[263:0];

  assign fwdIn_2 = c$vec_17[264-1 -: 132];

  assign c$vec_18 = result_27[133:132];

  assign bwdIn_1 = c$vec_18[2-1 -: 1];

  assign result_32 = {eth_Bwd,
                      \final:stmt_Fwd };

  assign eth_Fwd = result_20[131:0];

  assign \final:stmt_Bwd  = result_33[20:20];

  assign eth_Bwd = result_25[264:264];

  assign \final:stmt_Fwd  = result_27[131:0];

  assign result_33 = result_34[20:0];

  always @(*) begin
    case(eta2[133:132])
      2'b00 : result_34 = c$ds_case_alt_3;
      2'b01 : result_34 = c$ds_case_alt;
      default : result_34 = {c$ds_app_arg_3,   {1'b0,
                                                {1'b1,eta2[131:113]}}};
    endcase
  end

  assign c$ds_app_arg_3 = bwdIn_2 ? {2'b00,3'd0,{16 {8'b00000000}},1'b0} : eta2;

  assign c$ds_case_alt = c$ds23_app_arg[131:131] ? {c$ds_app_arg_5,
                                                    {bwdIn_2,   {1'b1,{ds8,   c$ds_app_arg_4,
                                                                       nextAborted_3}}}} : {eta2,   {bwdIn_2,
                                                                                                     {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_4 = newLast_1[2:2] ? c$ds_case_alt_0 : {1'b0,1'bx};

  assign c$ds_case_alt_selection_2 = newLast_1[1:0];

  assign c$ds_case_alt_0 = c$ds_case_alt_selection_2[1:1] ? {1'b0,1'bx} : {1'b1,x1_1};

  assign x1_1 = newLast_1[0:0];

  assign c$ds_app_arg_5 = bwdIn_2 ? c$ds_case_alt_1 : eta2;

  assign c$ds_case_alt_1 = newLast_1[2:2] ? c$ds_case_alt_2 : {2'b01,nextAborted_3,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds_case_alt_selection_6 = newLast_1[1:0];

  assign c$ds_case_alt_2 = c$ds_case_alt_selection_6[1:1] ? {2'b10,{{2 {8'b00000000}},
                                                                    {1'b1,idx_1},
                                                                    nextAborted_3},113'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,3'd0,{16 {8'b00000000}},1'b0};

  assign idx_1 = newLast_1[0:0];

  assign newLast_selection_10 = pkt[114:113];

  assign newLast_1 = newLast_selection_10[1:1] ? {1'b1,c$newLast_app_arg} : {1'b0,2'bxx};

  assign c$newLast_app_arg = {1'b0,a1_4 + 1'd0};

  assign a1_4 = pkt[113:113];

  assign nextAborted_3 = eta2[131:131] | pkt[0:0];

  assign ds8 = pkt[130:115];

  assign c$ds_case_alt_3 = c$ds23_app_arg[131:131] ? {c$ds_app_arg_6,
                                                      {1'b0,   {1'b1,{ds9[143:128],   {1'b0,1'bx},
                                                                      nextAborted_4}}}} : {eta2,   {bwdIn_2,
                                                                                                    {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_6 = bwdIn_2 ? c$ds_case_alt_4 : eta2;

  assign c$ds_case_alt_sel_alt_t_7 = pkt[130:115];

  assign c$ds_case_alt_4 = (eta2[131:129] == 3'd6) ? {2'b01,nextAborted_4,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,eta2[131:129] + 3'd1,ds9[127:0],nextAborted_4};

  assign nextAborted_4 = eta2[0:0] | pkt[0:0];

  assign ds9 = c$ds9_app_arg;

  assign c$ds9_app_arg_selection_1 = eta2[131:129];

  always @(*) begin
    case(c$ds9_app_arg_selection_1)
      3'd0 : c$ds9_app_arg = {({((result_35)),pkt[130:115]}),({2 {(8'd0)}})};
      default : c$ds9_app_arg = {eta2[128:1],({2 {(8'd0)}})};
    endcase
  end

  assign g1 = pkt[112:65];

  assign g2 = pkt[64:17];

  assign g3 = pkt[16:1];

  // map begin
  genvar i_27;
  generate
  for (i_27=0; i_27 < 6; i_27 = i_27 + 1) begin : map_9
    wire [7:0] map_in_10;
    assign map_in_10 = g2[i_27*8+:8];
    wire [7:0] map_out_10;
    assign map_out_10 = map_in_10;


    assign c$app_arg_11[i_27*8+:8] = map_out_10;
  end
  endgenerate
  // map end

  // map begin
  genvar i_28;
  generate
  for (i_28=0; i_28 < 6; i_28 = i_28 + 1) begin : map_10
    wire [7:0] map_in_11;
    assign map_in_11 = g1[i_28*8+:8];
    wire [7:0] map_out_11;
    assign map_out_11 = map_in_11;


    assign c$app_arg_12[i_28*8+:8] = map_out_11;
  end
  endgenerate
  // map end

  assign result_35 = ((({((((c$app_arg_12)))),(({((((c$app_arg_11)))),(g3)}))})));

  assign pkt = c$ds23_app_arg[130:0];

  // register begin
  always @(posedge ethTxClk ) begin : eta2_register
    if ( ! c$bindCsr) begin
      eta2 <= {2'b00,3'd0,{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000},1'b0};
    end else begin
      eta2 <= result_34[154:21];
    end
  end
  // register end

  assign bwdIn_2 = result_36[20:20];

  assign result_36 = result_37[20:0];

  always @(*) begin
    case(ds_0[6:5])
      2'b00 : result_37 = c$ds_case_alt_8;
      2'b01 : result_37 = c$ds_case_alt_6;
      default : result_37 = {c$ds_app_arg_8,   {1'b0,
                                                {1'b1,{{2 {8'b00000000}},   c$ds_app_arg_7,
                                                       1'b0}}}};
    endcase
  end

  assign c$ds_app_arg_7 = done ? {1'b1,1'd1} : {1'b0,1'bx};

  assign c$ds_app_arg_8 = bwd_1 ? c$ds_case_alt_5 : ds_0;

  assign c$ds_case_alt_5 = done ? {2'b00,5'd0} : {2'b10,i_1 + 5'd1};

  assign done = i_1 == 5'd29;

  assign i_1 = ds_0[4:0];

  assign c$ds_case_alt_selection_12 = result_33[19:0];

  assign c$ds_case_alt_6 = c$ds_case_alt_selection_12[19:19] ? {c$ds_app_arg_9,
                                                                {bwd_1,
                                                                 result_33[19:0]}} : {{2'b01,5'bxxxxx},
                                                                                      {bwd_1,
                                                                                       {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_9 = (bwd_1 & c$ds_case_alt_7) ? {2'b00,5'd0} : {2'b01,5'bxxxxx};

  assign c$ds_case_alt_selection_15 = fwdIn_3[2:1];

  assign c$ds_case_alt_7 = c$ds_case_alt_selection_15[1:1] ? 1'b1 : 1'b0;

  assign c$ds_case_alt_selection_18 = result_33[19:0];

  assign c$ds_case_alt_8 = c$ds_case_alt_selection_18[19:19] ? {c$ds_app_arg_12,
                                                                {bwd_1,   {1'b1,{fwdIn_3[18:3],
                                                                                 c$ds_app_arg_10,
                                                                                 fwdIn_3[0:0]}}}} : {ds_0,   {bwd_1,
                                                                                                              {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_10 = done_0 ? c$ds_case_alt_9 : {1'b0,1'bx};

  assign c$ds_case_alt_selection_21 = fwdIn_3[2:1];

  assign c$ds_case_alt_9 = c$ds_case_alt_selection_21[1:1] ? {1'b1,c$ds_app_arg_11} : {1'b0,1'bx};

  assign c$ds_app_arg_11 = (1'd1 <= a1_5) ? a1_5 : 1'd1;

  assign a1_5 = fwdIn_3[1:1];

  assign c$ds_app_arg_12 = bwd_1 ? c$ds_case_alt_10 : ds_0;

  assign bwd_1 = result_38[20:20];

  assign c$ds_case_alt_10 = done_0 ? c$ds_case_alt_11 : c$ds_case_alt_12;

  assign done_0 = i_2 == 5'd29;

  assign c$ds_case_alt_selection_25 = fwdIn_3[2:1];

  assign c$ds_case_alt_11 = c$ds_case_alt_selection_25[1:1] ? {2'b00,5'd0} : {2'b01,5'bxxxxx};

  assign c$ds_case_alt_selection_28 = fwdIn_3[2:1];

  assign c$ds_case_alt_12 = c$ds_case_alt_selection_28[1:1] ? {2'b10,c$ds_app_arg_13} : {2'b00,c$ds_app_arg_13};

  assign fwdIn_3 = result_33[18:0];

  assign c$ds_app_arg_13 = i_2 + 5'd1;

  assign i_2 = ds_0[4:0];

  // register begin
  always @(posedge ethTxClk ) begin : ds_0_register
    if ( ! c$bindCsr) begin
      ds_0 <= {2'b00,5'd0};
    end else begin
      ds_0 <= result_37[27:21];
    end
  end
  // register end

  assign result_38 = {c$case_alt_24[20:20],
                      result_39[20:1]};

  assign result_39 = ds6[55:55] ? {c$ds8_app_arg_10,
                                   {{1'b1,{ds15[47:32],   c$ds8_app_arg_9,
                                           ds6[54:54]}},   1'b0}} : c$ds8_case_alt_1;

  assign c$ds8_case_alt_selection_3 = ds6[54:35];

  assign c$ds8_case_alt_1 = c$ds8_case_alt_selection_3[19:19] ? {c$ds8_app_arg_7,
                                                                 {{1'b1,c$ds8_app_arg_6},
                                                                  r2sAc_4}} : {{1'b0,fwdIn_4,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx},
                                                                               {{1'b0,19'bxxxxxxxxxxxxxxxxxxx},
                                                                                1'b1}};

  assign c$ds8_app_arg_6 = insertCrc[2:2] ? {ds14[47:32],
                                             x_1,   cache_0[0:0]} : cache_0;

  assign c$ds8_app_arg_7 = r2sAc_4 ? c$ds8_case_alt_2 : ds6;

  assign c$ds8_case_alt_2 = insertCrc[2:2] ? c$ds8_case_alt_3 : {1'b0,fwdIn_4,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds8_case_alt_3 = x_1[1:1] ? {1'b0,fwdIn_4,35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {1'b1,cache_0[0:0],fwdIn_4,(({1'b0,(c$ds8_app_arg_8)}) - 2'b10),ds14[31:0]};

  assign x_1 = insertCrc[1:0];

  assign insertCrc_selection_1 = cache_0[2:1];

  assign insertCrc = insertCrc_selection_1[1:1] ? {1'b1,{1'b0,1'bx}} : {1'b0,2'bxx};

  assign ds14 = c$ds14_app_arg;

  assign c$ds14_app_arg_selection_1 = cache_0[2:1];

  assign c$ds14_app_arg = c$ds14_app_arg_selection_1[1:1] ? result_40 : ({48 {1'bx}});

  assign c$vec_19 = {{x1_3,result_41},   \xs' };

  // reverse begin
  genvar i_29;
  generate
  for (i_29 = 0; i_29 < 2; i_29 = i_29 + 1) begin : reverse
    assign c$app_arg_13[(2 - 1 - i_29)*48+:48] = c$vec_19[i_29*48+:48];
  end
  endgenerate
  // reverse end

  assign \xs'  = {x1_2,({result_41,({1 {8'b00000000}})})};

  assign x1_projection_5 = cache_0[18:3];

  assign x1_2 = x1_projection_5[15:8];

  assign x1_projection_6 = cache_0[18:3];

  assign x1_3 = x1_projection_6;

  // index begin
  wire [47:0] vecArray_2 [0:2-1];
  genvar i_30;
  generate
  for (i_30=0; i_30 < 2; i_30=i_30+1) begin : mk_array_2
    assign vecArray_2[(2-1)-i_30] = c$app_arg_13[i_30*48+:48];
  end
  endgenerate
  assign result_40 = vecArray_2[($unsigned({{(64-1) {1'b0}},a1_6}))];
  // index end

  assign c$ds8_app_arg_selection_16 = cache_0[2:1];

  assign c$ds8_app_arg_8 = c$ds8_app_arg_selection_16[1:1] ? (a1_6) : ({1 {1'bx}});

  assign a1_6 = cache_0[1:1];

  assign cache_0 = ds6[53:35];

  assign fwdIn_4 = c$case_alt_24[19:0];

  assign c$bv_3 = ds6[33:32];

  assign c$ds8_app_arg_9 = finished ? {1'b1,c$bv_3[0+:1]} : {1'b0,1'bx};

  assign c$ds8_app_arg_10 = r2sAc_4 ? c$ds8_case_alt_4 : ds6;

  assign r2sAc_4 = result_46[20:20];

  assign c$vec_20 = ((result_42));

  // reverse begin
  genvar i_31;
  generate
  for (i_31 = 0; i_31 < 4; i_31 = i_31 + 1) begin : reverse_0
    assign result_41[(4 - 1 - i_31)*8+:8] = c$vec_20[i_31*8+:8];
  end
  endgenerate
  // reverse end

  assign result_42 = 32'b11111111111111111111111111111111 ^ result_43;

  // map begin
  genvar i_32;
  generate
  for (i_32=0; i_32 < 32; i_32 = i_32 + 1) begin : map_11
    wire  map_in_12;
    assign map_in_12 = c$app_arg_15[i_32*1+:1];
    wire [0:0] map_out_12;
    assign map_out_12 = (map_in_12);


    assign c$app_arg_14[i_32*1+:1] = map_out_12;
  end
  endgenerate
  // map end

  assign result_43 = (c$app_arg_14);

  assign c$vec_21 = ((crcState_0));

  // reverse begin
  genvar i_33;
  generate
  for (i_33 = 0; i_33 < 32; i_33 = i_33 + 1) begin : reverse_1
    assign c$app_arg_15[(32 - 1 - i_33)*1+:1] = c$vec_21[i_33*1+:1];
  end
  endgenerate
  // reverse end

  // register begin
  always @(posedge ethTxClk ) begin : crcState_0_register
    if ( ! c$bindCsr) begin
      crcState_0 <= 32'b11111111111111111111111111111111;
    end else if (c$crcState_app_arg_1) begin
      crcState_0 <= c$crcState_case_alt;
    end
  end
  // register end

  assign c$crcState_case_alt_selection_1 = c$crcState_case_alt_selection_0;

  assign c$i_171 = ds11_1[16:16];

  assign c$crcState_case_alt_selection_0 = $unsigned({{(64-1) {1'b0}},c$i_171});

  always @(*) begin
    case(c$crcState_case_alt_selection_1)
      64'sd0 : c$crcState_case_alt = result_45;
      64'sd1 : c$crcState_case_alt = result_44;
      default : c$crcState_case_alt = {32 {1'bx}};
    endcase
  end

  // map begin
  genvar i_34;
  generate
  for (i_34=0; i_34 < 2; i_34 = i_34 + 1) begin : map_12
    wire [7:0] map_in_13;
    assign map_in_13 = x_2[i_34*8+:8];
    wire [7:0] map_out_13;
    assign map_out_13 = map_in_13;


    assign c$case_alt_23[i_34*8+:8] = map_out_13;
  end
  endgenerate
  // map end

  assign x_projection_5 = ds11_1[15:0];

  assign x_2 = x_projection_5;

  assign c$vec_22 = {48'b100010110010000010000000000000001101000100000100,
                     48'b010001011001000001000000000000001010001000001001,
                     48'b001000101100100000100000000000000100010000010011,
                     48'b000100010110010000010000000000001000100000100110,
                     48'b000010001011001000001000000000000001000001001101,
                     48'b000001000101100100000100000000000010000010011010,
                     48'b100010010000110000000010000000001001000100110000,
                     48'b010001001000011000000001000000000010001001100001,
                     48'b101000100100001100000000100000000100010111000010,
                     48'b010110100000000100000000010000000101101010000000,
                     48'b001001100010000000000000001000000110010000000100,
                     48'b000100110001000000000000000100001100100000001000,
                     48'b100010011000100000000000000010001001000100010001,
                     48'b110001001100010000000000000001000010001100100011,
                     48'b011000100110001000000000000000100100011001000110,
                     48'b001100010011000100000000000000011000110010001100,
                     48'b100100111011100000000000000000001100100100011101,
                     48'b110010011101110000000000000000001001001100111011,
                     48'b011001001110111000000000000000000010011001110111,
                     48'b101100100111011100000000000000000100110111101110,
                     48'b110100100001101100000000000000000100101111011000,
                     48'b011000100010110100000000000000000100011010110100,
                     48'b001110100011011000000000000000000101110001101100,
                     48'b000111010001101100000000000000001011100011011000,
                     48'b100001011010110100000000000000001010000110110101,
                     48'b010010011111011000000000000000001001001001101111,
                     48'b001001001111101100000000000000000010010011011111,
                     48'b100110010101110100000000000000001001100110111010,
                     48'b110001111000111000000000000000001110001101110001,
                     48'b011000111100011100000000000000001100011011100011,
                     48'b001110101100001100000000000000000101110011000011,
                     48'b000101100100000100000000000000000110100010000010};

  // map begin
  genvar i_35;
  generate
  for (i_35=0; i_35 < 32; i_35 = i_35 + 1) begin : map_13
    wire [47:0] map_in_14;
    assign map_in_14 = c$vec_22[i_35*48+:48];
    wire  map_out_14;
    assign map_out_14 = ^ (((({c$crcState_app_arg_0,((c$case_alt_23))}) & map_in_14)));


    assign c$app_arg_16[i_35*1+:1] = map_out_14;
  end
  endgenerate
  // map end

  assign result_44 = ((c$app_arg_16));

  assign x_projection_6 = ds11_1[15:0];

  assign x_3 = x_projection_6[15:8];

  assign c$vec_23 = {40'b0010000010000000000000000000000000000100,
                     40'b1001000001000000000000000000000000001001,
                     40'b1100100000100000000000000000000000010011,
                     40'b0110010000010000000000000000000000100110,
                     40'b1011001000001000000000000000000001001101,
                     40'b0101100100000100000000000000000010011010,
                     40'b0000110000000010000000000000000000110000,
                     40'b1000011000000001000000000000000001100001,
                     40'b0100001100000000100000000000000011000010,
                     40'b0000000100000000010000000000000010000000,
                     40'b0010000000000000001000000000000000000100,
                     40'b0001000000000000000100000000000000001000,
                     40'b1000100000000000000010000000000000010001,
                     40'b1100010000000000000001000000000000100011,
                     40'b0110001000000000000000100000000001000110,
                     40'b0011000100000000000000010000000010001100,
                     40'b1011100000000000000000001000000000011101,
                     40'b1101110000000000000000000100000000111011,
                     40'b1110111000000000000000000010000001110111,
                     40'b0111011100000000000000000001000011101110,
                     40'b0001101100000000000000000000100011011000,
                     40'b0010110100000000000000000000010010110100,
                     40'b0011011000000000000000000000001001101100,
                     40'b0001101100000000000000000000000111011000,
                     40'b1010110100000000000000000000000010110101,
                     40'b1111011000000000000000000000000001101111,
                     40'b1111101100000000000000000000000011011111,
                     40'b0101110100000000000000000000000010111010,
                     40'b1000111000000000000000000000000001110001,
                     40'b1100011100000000000000000000000011100011,
                     40'b1100001100000000000000000000000011000011,
                     40'b0100000100000000000000000000000010000010};

  // map begin
  genvar i_36;
  generate
  for (i_36=0; i_36 < 32; i_36 = i_36 + 1) begin : map_14
    wire [39:0] map_in_15;
    assign map_in_15 = c$vec_23[i_36*40+:40];
    wire  map_out_15;
    assign map_out_15 = ^ (((({c$crcState_app_arg_0,((x_3[7:0]))}) & map_in_15)));


    assign c$app_arg_17[i_36*1+:1] = map_out_15;
  end
  endgenerate
  // map end

  assign result_45 = ((c$app_arg_17));

  assign c$crcState_app_arg_0 = c$x_app_arg_1 ? 32'b11111111111111111111111111111111 : crcState_0;

  assign c$crcState_app_arg_1 = c$x_app_arg[17:17] ? 1'b1 : 1'b0;

  assign ds11_1 = c$x_app_arg[17:17] ? a1_7 : ({17 {1'bx}});

  assign a1_7 = c$x_app_arg[16:0];

  assign c$x_app_arg = transferOccured_0 ? {1'b1,{c$x_app_arg_0,
                                                  fwdInX_0[18:3]}} : {1'b0,17'bxxxxxxxxxxxxxxxxx};

  assign c$x_app_arg_selection_2 = fwdInX_0[2:1];

  assign c$x_app_arg_0 = c$x_app_arg_selection_2[1:1] ? v_0 : 1'd1;

  assign v_0 = fwdInX_0[1:1];

  // register begin
  always @(posedge ethTxClk ) begin : c$x_app_arg_1_register
    if ( ! c$bindCsr) begin
      c$x_app_arg_1 <= 1'b1;
    end else if (transferOccured_0) begin
      c$x_app_arg_1 <= c$x_case_alt;
    end
  end
  // register end

  assign c$x_case_alt_selection_1 = fwdInX_0[2:1];

  assign c$x_case_alt = c$x_case_alt_selection_1[1:1] ? 1'b1 : 1'b0;

  assign fwdInX_selection_2 = c$case_alt_24[19:0];

  assign fwdInX_0 = fwdInX_selection_2[19:19] ? a1_8 : ({19 {1'bx}});

  assign a1_8 = c$case_alt_24[18:0];

  assign transferOccured_0 = ready_0 & c$transferOccured_app_arg_0;

  assign ready_0 = result_39[0:0];

  assign c$transferOccured_app_arg_selection_2 = c$case_alt_24[19:0];

  assign c$transferOccured_app_arg_0 = c$transferOccured_app_arg_selection_2[19:19] ? 1'b1 : 1'b0;

  assign rstLow_3 = ~ (c$bindCsr);

  assign c$case_alt_24 = rstLow_3 ? {1'b0,
                                     {1'b0,19'bxxxxxxxxxxxxxxxxxxx}} : {ready_0,
                                                                        s2rAc_3};

  assign s2rAc_3 = result_36[19:0];

  assign c$ds8_case_alt_4 = finished ? {1'b0,ds6[53:34],35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {1'b1,ds6[54:54],ds6[53:34],ds6[33:32] - 2'd2,ds15[31:0]};

  assign finished = ds6[33:32] <= 2'd1;

  assign ds15 = ({ds6[31:0],({2 {8'b00000000}})});

  // register begin
  always @(posedge ethTxClk ) begin : ds6_register
    if ( ! c$bindCsr) begin
      ds6 <= {1'b0,{1'b0,19'bxxxxxxxxxxxxxxxxxxx},35'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else begin
      ds6 <= result_39[76:21];
    end
  end
  // register end

  assign result_46 = result_47[20:0];

  always @(*) begin
    case(eta2_0[84:83])
      2'b00 : result_47 = c$ds_case_alt_17;
      2'b01 : result_47 = c$ds_case_alt_13;
      default : result_47 = {c$ds_app_arg_14,
                             {1'b0,   {1'b1,eta2_0[82:64]}}};
    endcase
  end

  assign c$ds_app_arg_14 = bwdIn_3 ? {2'b00,2'd0,{10 {8'b00000000}},1'b0} : eta2_0;

  assign c$ds_case_alt_selection_31 = result_38[19:0];

  assign c$ds_case_alt_13 = c$ds_case_alt_selection_31[19:19] ? {c$ds_app_arg_16,
                                                                 {bwdIn_3,   {1'b1,{ds8_0,   c$ds_app_arg_15,
                                                                                    nextAborted_5}}}} : {eta2_0,
                                                                                                         {bwdIn_3,
                                                                                                          {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_15 = newLast_2[2:2] ? c$ds_case_alt_14 : {1'b0,1'bx};

  assign c$ds_case_alt_selection_34 = newLast_2[1:0];

  assign c$ds_case_alt_14 = c$ds_case_alt_selection_34[1:1] ? {1'b0,1'bx} : {1'b1,x1_4};

  assign x1_4 = newLast_2[0:0];

  assign c$ds_app_arg_16 = bwdIn_3 ? c$ds_case_alt_15 : eta2_0;

  assign c$ds_case_alt_15 = newLast_2[2:2] ? c$ds_case_alt_16 : {2'b01,nextAborted_5,82'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$ds_case_alt_selection_38 = newLast_2[1:0];

  assign c$ds_case_alt_16 = c$ds_case_alt_selection_38[1:1] ? {2'b10,{{2 {8'b00000000}},
                                                                      {1'b1,idx_2},
                                                                      nextAborted_5},64'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,2'd0,{10 {8'b00000000}},1'b0};

  assign idx_2 = newLast_2[0:0];

  assign newLast_selection_13 = pkt_0[2:1];

  assign newLast_2 = newLast_selection_13[1:1] ? {1'b1,c$newLast_app_arg_0} : {1'b0,2'bxx};

  assign c$newLast_app_arg_0 = {1'b0,a1_9 + 1'd0};

  assign a1_9 = pkt_0[1:1];

  assign nextAborted_5 = eta2_0[82:82] | pkt_0[0:0];

  assign ds8_0 = pkt_0[18:3];

  assign c$ds_case_alt_selection_41 = result_38[19:0];

  assign c$ds_case_alt_17 = c$ds_case_alt_selection_41[19:19] ? {c$ds_app_arg_17,
                                                                 {1'b0,   {1'b1,{ds9_0[95:80],   {1'b0,1'bx},
                                                                                 nextAborted_6}}}} : {eta2_0,
                                                                                                      {bwdIn_3,
                                                                                                       {1'b0,19'bxxxxxxxxxxxxxxxxxxx}}};

  assign c$ds_app_arg_17 = bwdIn_3 ? c$ds_case_alt_18 : eta2_0;

  assign c$ds_case_alt_sel_alt_t_28 = pkt_0[18:3];

  assign c$ds_case_alt_18 = (eta2_0[82:81] == 2'd3) ? {2'b01,nextAborted_6,82'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : {2'b00,eta2_0[82:81] + 2'd1,ds9_0[79:0],nextAborted_6};

  assign nextAborted_6 = eta2_0[0:0] | pkt_0[0:0];

  assign ds9_0 = c$ds9_app_arg_0;

  assign c$ds9_app_arg_selection_4 = eta2_0[82:81];

  assign c$vec_24 = ({({7 {8'b01010101}}),8'b11010101});

  // map begin
  genvar i_37;
  generate
  for (i_37=0; i_37 < 8; i_37 = i_37 + 1) begin : map_15
    wire [7:0] map_in_16;
    assign map_in_16 = c$vec_24[i_37*8+:8];
    wire [7:0] map_out_16;
    assign map_out_16 = map_in_16;


    assign c$ds9_app_arg_sel_alt_res[i_37*8+:8] = map_out_16;
  end
  endgenerate
  // map end

  always @(*) begin
    case(c$ds9_app_arg_selection_4)
      2'd0 : c$ds9_app_arg_0 = {({((((c$ds9_app_arg_sel_alt_res)))),pkt_0[18:3]}),({2 {(8'd0)}})};
      default : c$ds9_app_arg_0 = {eta2_0[80:1],({2 {(8'd0)}})};
    endcase
  end

  assign pkt_0 = result_38[18:0];

  // register begin
  always @(posedge ethTxClk ) begin : eta2_0_register
    if ( ! c$bindCsr) begin
      eta2_0 <= {2'b00,2'd0,{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
               8'b00000000,   8'b00000000},1'b0};
    end else begin
      eta2_0 <= result_47[105:21];
    end
  end
  // register end

  assign bwdIn_3 = result_48[11:11];

  assign result_48 = {c$case_alt_25[20:20],
                      c$ds8_app_arg_11};

  assign c$vec_25 = st_0[19:4];

  assign c$ds8_app_arg_11 = c$ds11_app_arg ? {1'b1,{c$vec_25[16-1 -: 8],
                                                    c$ds8_app_arg_12,
                                                    st_0[0:0]}} : {1'b0,10'bxxxxxxxxxx};

  assign c$ds8_app_arg_12 = (c$outReady_app_arg & st_0[1:1]) ? 1'd1 : 1'd0;

  assign result_selection_29 = c$case_alt_25[19:0];

  assign result_49 = result_selection_29[19:19] ? c$ds8_case_alt_5 : {ds11_2[15:0],
                                                                      ds11_2[17:16],   st_0[1:1],   st_0[0:0]};

  assign c$ds8_case_alt_5 = outReady ? {vs,
                                        c$ds8_app_arg_14,   c$ds8_app_arg_13,
                                        aborted} : {ds11_2[15:0],   ds11_2[17:16],
                                                    st_0[1:1],   st_0[0:0]};

  assign outReady = (st_0[3:2] == 2'd0) | (c$outReady_app_arg & r2sAc_5);

  assign c$outReady_app_arg = st_0[3:2] == 2'd1;

  assign aborted = inp[0:0];

  assign vs = inp[18:3];

  assign c$ds8_app_arg_13 = lastIdx[1:1] ? 1'b1 : 1'b0;

  assign c$ds8_app_arg_14 = lastIdx[1:1] ? (({{(2-1) {1'b0}},x_4}) + 2'd1) : 2'd2;

  assign x_4 = lastIdx[0:0];

  assign lastIdx = inp[2:1];

  assign inp = c$case_alt_25[18:0];

  assign ds11_sel_alt_t_1 = ({st_0[19:4],8'b00000000});

  assign ds11_2 = (c$ds11_app_arg & r2sAc_5) ? {st_0[3:2] - 2'd1,
                                                ds11_sel_alt_t_1[15:0]} : {st_0[3:2],
                                                                           st_0[19:4]};

  assign r2sAc_5 = result_51[11:11];

  assign c$ds11_app_arg = st_0[3:2] > 2'd0;

  // register begin
  always @(posedge ethTxClk ) begin : st_0_register
    if ( ! c$bindCsr) begin
      st_0 <= {{16 {1'bx}},   2'd0,   1'b0,   1'b0};
    end else begin
      st_0 <= result_49;
    end
  end
  // register end

  assign rstLow_4 = ~ (c$bindCsr);

  assign c$case_alt_25 = rstLow_4 ? {1'b0,
                                     {1'b0,19'bxxxxxxxxxxxxxxxxxxx}} : {outReady,
                                                                        s2rAc_4};

  assign s2rAc_4 = result_46[19:0];

  assign c$ds_app_arg_18 = (ds1_0[3:0] == 4'd11) ? {1'b1,4'bxxxx} : {1'b0,ds1_0[3:0] + 4'd1};

  assign c$ds_case_alt_19 = inp_0[1:1] ? {1'b0,4'd0} : {1'b1,4'bxxxx};

  assign c$ds_case_alt_selection_47 = result_48[10:0];

  assign c$ds_case_alt_20 = c$ds_case_alt_selection_47[10:10] ? {c$ds_case_alt_19,
                                                                 {r2sAc_6,
                                                                  result_48[10:0]}} : {{1'b1,4'bxxxx},
                                                                                       {r2sAc_6,
                                                                                        {1'b0,10'bxxxxxxxxxx}}};

  assign result_50 = ds1_0[4:4] ? c$ds_case_alt_20 : {c$ds_app_arg_18,
                                                      {1'b0,   {1'b0,10'bxxxxxxxxxx}}};

  assign result_51 = result_50[11:0];

  // register begin
  always @(posedge ethTxClk ) begin : ds1_0_register
    if ( ! c$bindCsr) begin
      ds1_0 <= {1'b1,4'bxxxx};
    end else begin
      ds1_0 <= result_50[16:12];
    end
  end
  // register end

  assign inp_0 = result_48[9:0];

  assign r2sAc_6 = result_54[6:6];

  assign c$ds23_app_arg_selection_1 = result_32[131:0];

  assign c$ds23_app_arg = c$ds23_app_arg_selection_1[131:131] ? {1'b1,{a1_10[130:115],
                                                                       a1_10[114:113],   {a1_10[64:17],
                                                                                          {8'b01011110,   8'b10100100,
                                                                                           8'b01001110,   8'b11110100,
                                                                                           8'b00100001,   8'b00000110},
                                                                                          a1_10[16:1]},
                                                                       a1_10[0:0]}} : {1'b0,131'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign a1_10 = result_32[130:0];

  // register begin
  always @(posedge ethRxClk ) begin : c$ds_app_arg_19_register
    if ( ! c$app_arg) begin
      c$ds_app_arg_19 <= ({4 {1'bx}});
    end else begin
      c$ds_app_arg_19 <= nibble0;
    end
  end
  // register end

  // register begin
  always @(posedge ethRxClk ) begin : c$ds_app_arg_20_register
    if ( ! c$app_arg) begin
      c$ds_app_arg_20 <= 1'b0;
    end else begin
      c$ds_app_arg_20 <= dv0;
    end
  end
  // register end

  assign result_52 = (c$ds_app_arg_20 & (~ dv0)) ? 1'd1 : 1'd0;

  // delay begin
  always @(posedge ethRxClk) begin : c$ds3_app_arg_3_delay
    c$ds3_app_arg_3 <= rxChannel[4:4];
  end
  // delay end

  assign result_53 = dv0 ? {1'b1,{{nibble0,c$ds_app_arg_19},
                                  result_52,   ds3}} : {1'b0,10'bxxxxxxxxxx};

  assign c$case_alt_26 = result_53;

  // delay begin
  always @(posedge ethRxClk) begin : dv0_delay
    dv0 <= rxChannel[5:5];
  end
  // delay end

  // delay begin
  always @(posedge ethRxClk) begin : nibble0_delay
    nibble0 <= rxChannel[3:0];
  end
  // delay end

  // register begin
  always @(posedge ethRxClk ) begin : ds3_register
    if ( ! c$app_arg) begin
      ds3 <= ({1 {1'bx}});
    end else begin
      ds3 <= c$ds3_app_arg_3;
    end
  end
  // register end

  assign result_54 = {inputVld & nibbleSelect,
                      {c$app_arg_22,   c$app_arg_20,
                       c$app_arg_18}};

  // delay begin
  always @(posedge ethTxClk) begin : c$app_arg_18_delay
    c$app_arg_18 <= c$app_arg_19;
  end
  // delay end

  assign c$app_arg_19 = nibbleSelect ? ds2_0[3:0] : ds2_0[7:4];

  assign ds2_0 = (c$ds2_app_arg_13);

  // delay begin
  always @(posedge ethTxClk) begin : c$app_arg_20_delay
    c$app_arg_20 <= c$app_arg_21;
  end
  // delay end

  assign c$app_arg_selection_12 = result_0[10:0];

  assign c$app_arg_21 = c$app_arg_selection_12[10:10] ? a1_11[0:0] : 1'b0;

  // delay begin
  always @(posedge ethTxClk) begin : c$app_arg_22_delay
    c$app_arg_22 <= inputVld;
  end
  // delay end

  // register begin
  always @(posedge ethTxClk ) begin : nibbleSelect_register
    if ( ! c$bindCsr) begin
      nibbleSelect <= 1'b0;
    end else if (inputVld) begin
      nibbleSelect <= (~ nibbleSelect);
    end
  end
  // register end

  assign inputVld_selection_1 = result_0[10:0];

  assign inputVld = inputVld_selection_1[10:10] ? 1'b1 : 1'b0;

  assign c$ds2_app_arg_selection_23 = result_0[10:0];

  assign c$vec_26 = a1_11[9:2];

  assign c$ds2_app_arg_13 = c$ds2_app_arg_selection_23[10:10] ? (c$vec_26[8-1 -: 8]) : ({8 {1'bx}});

  assign a1_11 = result_0[9:0];

  assign result_55 = result_54[5:0];

  assign result = result_55;

  assign txEn = result[5:5];

  assign txErr = result[4:4];

  assign txData = result[3:0];


endmodule

